### ISSUE TITLE
Provide capability to track a IoT Hub dependency based on connection string information

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#109]
Provide capability to track a IoT Hub dependency based on connection string information.

Information can be resolved via [`IotHubConnectionStringBuilder.Create`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.iothubconnectionstringbuilder.create?view=azure-dotnet#Microsoft_Azure_Devices_Client_IotHubConnectionStringBuilder_Create_System_String_).

**Comment by stijnmoreels** [comment]
Cool! Only a pity that we have to install additional NuGet packages to access this resulting that every non-IoT Hub project will have those NuGet packages when using this (`Arcus.Observability.Telemetry.Core`) package.

**Comment by stijnmoreels** [comment]
So, what should we do with this? 🤔 Separate libraries?

**Comment by tomkerkhove** [comment]
I don't have an issue with it since we already do it for SQL like you've mentioned, but maybe others do @fgheysels @gverstraete @mbraekman

**Comment by mbraekman** [comment]
Shouldn't we try to limit the amount of dependencies? 
Personally, I don't really like having a project that references an IoT-package for instance, while nothing in the entire project has got anything to do with IoT.
Also, I always get the shivers when seeing a long list of dependencies before importing a package, makes we wonder how much of it I really need.

**Comment by fgheysels** [comment]
I'm totally with @mbraekman  :)

I'm not a fan of splitting up functionality in multiple packages when it's not necessary (I think I once had such a comment regarding Arcus Security) :).  When core functionality that belongs together can be grouped together, I think that must be done.

However, in this case, where you have dependency trackes for resources that you might not require, I'm in favor of splitting it in multiple packages.   (Just like what MS does with their ConfigurationProviders f.i.)

**Comment by tomkerkhove** [comment]
Ok for me, let's make it so! But let's align SQL then as well @stijnmoreels

**Comment by stijnmoreels** [comment]
> Ok for me, let's make it so! But let's align SQL then as well @stijnmoreels

Already on it! 👊

**Comment by stijnmoreels** [comment]
Practical question: if we move the SQL and IoT logging extensions to separate libraries, should we then move the extensions of both tech (that don't use the dependency packages) also to the separate library?

For example: the SQL has extensions where we manually pass allong the connection string info and where we select the info from an existing connection string. 
Should both extensions then be moved to the separate library? Or ony the ones where we use the dependency NuGet package?

**Comment by stijnmoreels** [comment]
Bc, if we move both, it means that you don't have access anymore to the 'default' extensions and since SQL Dependency is a default dependency type it seems bit weird to not include it in our 'core' library?

**Comment by tomkerkhove** [comment]
We should only move out the ones where you rely on the package; otherwise you force people to pull in another dependency even if they want to provide the info manually (and thus not even using that dependency)

**Comment by stijnmoreels** [comment]
Ok!

> We should only move out the ones where you rely on the package; otherwise you force people to pull in another dependency even if they want to provide the info manually (and thus not even using that dependency)

Ok!
