### ISSUE TITLE
Do we expect people to provide Machine Name or do we help them?

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#110]
Our Application Insights sink automatically assigned `CloudContext.RoleInstance` based on either pod name or machine name ([code](https://github.com/arcus-azure/arcus.observability/blob/master/src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CloudContextConverter.cs#L27)).

However, for Machine Name you have to know to use [Serilog.Enrichers.Environment](https://github.com/serilog/serilog-enrichers-environment) but have to know that we depend on this.

So I'm wonderin:
- Should we just document this and add it to our templates, or
- Should we base our [`ApplicationEnricher`](https://github.com/arcus-azure/arcus.observability/blob/master/src/Arcus.Observability.Telemetry.Serilog.Enrichers/ApplicationEnricher.cs) on it and extend it?

**Comment by stijnmoreels** [comment]
Seens like something for in the `ApplicationEnricher`, no?

**Comment by tomkerkhove** [comment]
I think building `ApplicationEnricher` on `Serilog.Enrichers.Environment` is best indeed!
