### ISSUE TITLE
Log context as "Context", not "EventDescription"

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#114]
**Is your feature request related to a problem? Please describe.**
All our extensions are using `EventContext` which maps to `EventDescription` which is a bit odd: https://github.com/arcus-azure/arcus.observability/blob/4964df2b79ddd40e3ca1191c65c442f2e74ab4b7/src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs#L24

**Describe the solution you'd like**
Log context as "Context", not "EventDescription" to be more agnostic.

**Comment by stijnmoreels** [comment]
Wondering... when consumers would use `EventDescription` up until now from the message template directly or from maybe custom converters... would renaming this not be a breaking change? In other words: can this be in v0.3?

**Comment by tomkerkhove** [comment]
I think it's ok to do this as part of v0.3, we can keep populating `EventDescription` for non-events and deprecate that.

**Comment by stijnmoreels** [comment]
Hmm, not entirly sure if I get your proposal 😅 . Care to give an example or more info. Thanks!

**Comment by tomkerkhove** [comment]
What we should do is:
- Introduce `TelemetryContext` or `Context` and use that for our enrichment
- Still use `EventDescription` for events
- Deprecate `EventDescription` for non-events, but still include it in the telemetry context to not break any logic on it
- Remove all enrichment logic based on `EventDescription`

**Comment by stijnmoreels** [comment]
Ok, let's try that.
