### ISSUE TITLE
Not all dimensions are tracked for metrics

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#118]
**Is your feature request related to a problem? Please describe.**
Not all dimensions are tracked for metrics when doing this:
```csharp
var repoName = _configuration["DOCKER_HUB_REPO_NAME"];
var imageName = _configuration["DOCKER_HUB_IMAGE_NAME"];

var imageMetrics = await _dockerHubClient.GetImageMetricsAsync(repoName, imageName);

var contextualInformation = new Dictionary<string, object>
{
    {"Repo Name", repoName},
    {"Image Name", imageName},
    {"Image ID", $"{repoName}/{imageName}"}
};

_logger.LogMetric("Image Pulls", imageMetrics.Pulls, contextualInformation);
_logger.LogMetric("Image Stars", imageMetrics.Stars, contextualInformation);
```

Is it me missing something obvious or is this a bug?

**Additional context**
Logged outcome in Application Insights:
`2020-05-18T13:27:06.0860038Z,"Image Pulls",254859,1,254859,254859,254859,"{""version"":""1.0.0"",""MessageTemplate"":""Metric {MetricName}: {MetricValue} (Context: {@EventDescription})"",""ComponentName"":""Docker Hub Metrics Scraper"",""SourceContext"":""WorkerService1.Worker""}","1.0.0",PC,"0.0.0.0",Aartrijke,"West Flanders Province",Belgium,"Docker Hub Metrics Scraper",TomKerkhove,"eb57a4c7-6805-42bc-be92-7e19d37b29f7","temporary-instance","41326a9b-1f2a-45a3-b3a4-1ae97ad490cd","dotnetc:2.13.1-12554"`

**Comment by tomkerkhove** [comment]
Any news on this @stijnmoreels?

**Comment by stijnmoreels** [comment]
> Any news on this @stijnmoreels?

Honestly not yet looked at 😟 . Was mostly working on invictus-testing framework and AS4 issue and now shifting to the scripting repo.

**Comment by stijnmoreels** [comment]
You mean that the context isn't logged?

**Comment by tomkerkhove** [comment]
> You mean that the context isn't logged?

Yes, the 3 contextual properties are not tracked nor available as dimension on the metric 🤔

**Comment by stijnmoreels** [comment]
Hmm, when I look at the tests (that also include contextual information), then I can find this on the portal:
![image](https://user-images.githubusercontent.com/9039753/83388302-80ff9980-a3ee-11ea-9b07-cf7ff142c3eb.png)

Or is this not the way to do it?

**Comment by tomkerkhove** [comment]
Hm odd, maybe it's a Azure Function thingy 🤔  Does it work with spaces as well?

**Comment by tomkerkhove** [comment]
I've just remembered that this was tested in a .NET Core worker as well where it didn't work as well I think.

Serilog config can be found here:
https://github.com/tomkerkhove/docker-hub-metrics-scraper/blob/master/src/DockerHub.Metrics.Runtime.AzureFunction/Startup.cs#L23

**Comment by stijnmoreels** [comment]
Seems like special charachters requires `[` `]` surrounded.
https://github.com/MicrosoftDocs/azure-docs/pull/7088/files

**Comment by tomkerkhove** [comment]
So you're saying that the above code worked for you? 🤔

**Comment by stijnmoreels** [comment]
> So you're saying that the above code worked for you? 🤔

Yes, 😅 .

**Comment by tomkerkhove** [comment]
So I started digging.

Our current unit test will write this as property:
`{[("Repo Name": "tomkerkhove"), ("Image Name": "promitor-agent-scraper")]}`

While if I do this in Azure Functions, it will use this property:
`{"[Repo Name, tomkerkhove], [Image Name, promitor-agent-scraper], [Image ID, tomkerkhove/promitor-agent-scraper]"}`

🤔 

Digging deeper.

**Comment by tomkerkhove** [comment]
Here's a repro of same issue without Azure Functions - https://github.com/tomkerkhove/arcus-dimensions-repro

**Comment by stijnmoreels** [comment]
> Here's a repro of same issue without Azure Functions - https://github.com/tomkerkhove/arcus-dimensions-repro

The `Context` here is not gonna work, right? It has to be `EventDescription` if you're using version v2.1.0

**Comment by tomkerkhove** [comment]
You are correct, my bad!

Updated and still reproducable. Like [mentioned above](https://github.com/arcus-azure/arcus.observability/issues/118#issuecomment-652211897), you can see that the property is not settings the property as a dictionary but more as a big string so I'm flagging this as a bug.

**Comment by stijnmoreels** [comment]
So, we can close this then? Since the problem was resolved?

**Comment by tomkerkhove** [comment]
No, I should document this and maybe we should consider moving [this code](https://github.com/tomkerkhove/docker-hub-metrics-scraper/blob/master/src/DockerHub.Metrics.Runtime.AzureFunction/Extensions/ILoggingBuilderExtensions.cs#L9) to Arcus?

**Comment by stijnmoreels** [comment]
> Maybe we should consider moving [this code](https://github.com/tomkerkhove/docker-hub-metrics-scraper/blob/master/src/DockerHub.Metrics.Runtime.AzureFunction/Extensions/ILoggingBuilderExtensions.cs#L9) to Arcus?

Yes, we can do that! Like `Arcus.Observability.Telemetry.AzureFunctions.Extensions`?

**Comment by tomkerkhove** [comment]
Yes, that sounds good to me.

**Comment by stijnmoreels** [comment]
Working on it! Was looking for the right packages that contains the necessary logging providers that we want to remove, so we can test it.
