### ISSUE TITLE
Provide a simple 'getting started' page in the documentation

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#119]
I'm sure Arcus Observability enables a bunch of interesting features to the table, but it would be nice if there's a simple 'getting started' section which describes how you can start using Arcus.

Actually, it is not very clear for me right now on how I could use this package in an existing API project.

**Comment by stijnmoreels** [comment]
Are you up to writing a proposal for this? As it would be better that this kind of page is written by someone that hasn't written the code.

**Comment by tomkerkhove** [comment]
We will add this for sure, in meantime, you can read https://www.codit.eu/blog/announcing-arcus-observability/

**Comment by fgheysels** [comment]
When I open the Observability documentation, I'd like to be able to quickly find how I should setup logging using ARcus.Observability.
This should actually be really one of the first things that you encounter when opening the documentation page.

There is documentation on who to set it up in Azure Functions, but we should have something similar on how to set it up in WebApi projects.
These 2 pages (How to set it up) should be really easy to find when you navigate to the Observability site.  They should be the first thing a visitor sees.
