### ISSUE TITLE
Metrics are not being tracked as I expected

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#120]
When quickly going through the documention, I'd assume that having this:

```csharp
.ConfigureLogging(logging =>
{
    logging.AddApplicationInsights();
});
```

and this:

```csharp
_logger.LogMetric("Some metric", 17);
```
would result in having a metric written to application insights.

However, in this case, the metric is just written to Application Insights as an information message.  It seems that this is only working when also using the Serilog sink, but that is IMHO not entire clear in the documentation.

**Comment by stijnmoreels** [comment]
Yes, the `.AddApplicationInsights` is the one available from Serilog but doesn't support all telemetry types. That's why we implemented our own with `.AddAzureApplicationInsights` building on top of that.

**Comment by tomkerkhove** [comment]
Did this fix your issue @fgheysels ?

**Comment by fgheysels** [comment]
I guess it has fixed the issue if i remember well.
However, the documentation might be extended to make that clear (if this is not already the case)

**Comment by tomkerkhove** [comment]
Isn't this enough? https://observability.arcus-azure.net/features/sinks/azure-application-insights

**Comment by fgheysels** [comment]
Hmm, in hindsight yes.  I think that should do it.
