### ISSUE TITLE
Move SQL dependency tracking to separate library

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#131]
**What feature do you want?**
Introduce a separate SQL package as part of v1.0 instead of relying on the SQL NuGet package now present in the Core library.

_Originally posted by @tomkerkhove in https://github.com/arcus-azure/arcus.observability/pull/130_

**Comment by tomkerkhove** [comment]
We can already do this, no? We just deprecate the current one and point to the new one?
