### ISSUE TITLE
Provide operation and transaction ID pattern in the correlation options to force consumers to think about formatting

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#138]
**Is your feature request related to a problem? Please describe.**
We could provide a pattern for the two ID's that you could pass along in the options (maybe also a method on the options to actually validate the input), so consumers can first of all provide some extra format that the correlation ID's should uphold + it lets them think about input validation and what's considered valid/invalid.

**Describe the solution you'd like**
The `CorrelationInfoOptions.Transaction` and `CorrelationInfoOptions.Operation` properties could both have a `Pattern` or `Format` property that's a `string` (maybe in the background checked for a valid regular expression).
An extra method on the options such as `PassFormat`, `IsWithinFormat`, `MatchesPattern`, ... can be added so the actual correlation implementation that uses this library can benefit from this.

**Describe alternatives you've considered**
Format validation can happen specifically on the correlation implemenation itself, or can complementair with is here proposed.

**Comment by tomkerkhove** [comment]
What would be the use-case for this?

**Comment by stijnmoreels** [comment]
> What would be the use-case for this?

You mean like an example? Bc the issue describes like the reason why this could be useful. It's about input validation and that we can provide some format in the configuration options (just like we provide some other options).

**Comment by tomkerkhove** [comment]
So this would be for validation of specified transaction IDs in headers for example or? I'm not sure I'm really following because majority of scenarios we generate the correlation info except for that

**Comment by stijnmoreels** [comment]
> So this would be for validation of specified transaction IDs in headers for example or? I'm not sure I'm really following because majority of scenarios we generate the correlation info except for that

Yes, the transaction ID and operation ID format. It's on the receiving side, and before we use those ID's in (logging, or any other part of the application), we should make sure that they pass a certain criteria. We didn't checked much on the ID's itself because this is application specific, so that's why I'm proposing on a format. Just using header values without any safety checks (not just non-null or non-blank) is not very safe.

**Comment by tomkerkhove** [comment]
Frankly, I don't expect much trouble on this side and might becoming too complex which makes it too hard to use.

What if we keep this open until we have demand for this to better design the feature?

**Comment by stijnmoreels** [comment]
Ok, we can do that. It's just something (the valiation) that has to happen anyway in any application to be safe, so it seemed like something we would want to include here. But is OK to leave it open.

**Comment by stijnmoreels** [comment]
Close in favor of: https://github.com/arcus-azure/arcus.observability/discussions/177
