### ISSUE TITLE
Provide extension on Serilog to log requests

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#14]
Provide extension on Serilog to log requests:

Ideas are:
```csharp
logger.LogRequest(httpContext.Request, httpContext.Response, duration);
```

Extension should allow you to provide contextual information by passing a dictionary, but should not be mandatory.

It should seemlessly integrate with the Azure Application Insight sink and track it as a "Request".

A sample by Tom will be provided as a starting point.

**Comment by stijnmoreels** [comment]
Done?
