### ISSUE TITLE
Provide capability to inject app version

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#143]
**Is your feature request related to a problem? Please describe.**
Provide capability to inject app version and use the information ourselves.

**Describe the solution you'd like**
We can refactor out the version determination from `VersionEnricher` and provide an `IAppVersion` which can be injected in the enriched and other application code.

**Comment by stijnmoreels** [comment]
Ah, yes, that can be useul if you want to control this outside assembly versions.
