### ISSUE TITLE
Provide support for Azure Functions in `AssemblyAppVersion`

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#146]
**Is your feature request related to a problem? Please describe.**
Provide support for Azure Functions in `AssemblyAppVersion` because it's now reporting the version of Azure Functions, not the app itself.

**Describe the solution you'd like**
Today we are using `Assembly.GetEntryAssembly()` which gives the version of the app that runs because `Assembly.GetExecutingAssembly()` reports the version of Arcus when it's used through a NuGet package.

Unfortunately, Azure Functions loads our customer code at runtime given the Azure Functions runtime is the entry point and thus it's reporting that version.

Maybe we should use `Assembly.GetAssembly(typeof(SomeCustomerType))` to determine the version of the app. Ideally the user does not have to provide the type to load and we detect that automatically when calling `WithVersion`.

**Describe alternatives you've considered**
None, but open to anything!

**Comment by stijnmoreels** [comment]
We could use the `StackFrame` to retrieve the previously called method and so eventually get the type and the assembly from where it was located; but if we create the `AssemblyAppVersion` ourselves (like, when there's none define and we use this as default), then we're back at our own assembly 😓.

**Comment by stijnmoreels** [comment]
So, propably have to pass along a consumer type ☹️ .

**Comment by tomkerkhove** [comment]
For me that's fine if we have to pass a consumer type.
