### ISSUE TITLE
Provide extension on Serilog to log custom events

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#15]
Provide extension on Serilog to log custom events:

Ideas are:
```csharp
var context = new Dictionary<string, object>
{
    {ContextProperties.Networking.OldNetworkStatus, oldStatus ?? NetworkStatus.Unknown},
    {ContextProperties.Networking.NetworkStatus, newStatus}
};

_logger.LogEvent("Network Connectivity Changed", context);
```

Extension should allow you to provide contextual information by passing a dictionary, but should not be mandatory.

It should seemlessly integrate with the Azure Application Insight sink and track it as a "Custom Event".

A sample by Tom will be provided as a starting point.

**Comment by tomkerkhove** [comment]
This was done in #40 and documentation is up on https://observability.arcus-azure.net/features/writing-different-telemetry-types#events, ok if we close @stijnmoreels?

**Comment by stijnmoreels** [comment]
> This was done in #40 and documentation is up on https://observability.arcus-azure.net/features/writing-different-telemetry-types#events, ok if we close @stijnmoreels?

Same, should we have some integration tests with Application Insights?

**Comment by tomkerkhove** [comment]
We need to add tests indeed, but only unit tests given we rely on Serilog to handle the rest

**Comment by stijnmoreels** [comment]
Done?
