### ISSUE TITLE
Azure Application Insights Sink for Arcus Observability output telemetry when restrictedToMinimumLevel is set to Warning

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.observability#154]
When restrictedToMinimumLevel is set to Warning for the Application Insights sink the telemetry data is not sent to Application Insights. This is set as follows:
`.WriteTo.AzureApplicationInsights(instrumentationKey, Serilog.Events.LogEventLevel.Information)`

I would like the telemetry data (dependancies, events, metrics, requests) to be sent to Application Insights regardless of the restrictedToMinimumLevel setting. 

An alternative could be an overload for the WriteTo.AzureApplicationInsights where we can set a parameter whether or not to sent the telemetry data regardless of the restrictedToMinimumLevel setting.

**Comment by tomkerkhove** [comment]
I think this makes sense as you'd want them to always be there unless you filter them out. What are your expectations, however, for the console logs?

**Comment by pim-simons** [comment]
Good question, my main source of logging info is Application Insights, which is why I mentioned Application Insights. However I think it would be good to have the same logic for console logs and Application Insights, if possible.

**Comment by stijnmoreels** [comment]
Not sure if I'm following. Is there a problem on our end? What should/could be changed?

**Comment by tomkerkhove** [comment]
@stijnmoreels We write all extensions for Event, Metric, et all as Info messages. So if you filter out all telemetry to just warnings, you won't see them.

Given people don't control how those extensions are written, you'd expect them to always show up and I agree. Maybe we should log them as warning instead. If you filter on critical only, then I think it's fair to say they won't be there

**Comment by stijnmoreels** [comment]
Aha, yeah. But warning may polute the console logs then, no? Warnings that are not exactly warnings. 🤔 Traces is also not an option, I guess since warning is below trace..

**Comment by tomkerkhove** [comment]
That's why I was asking @pim-simons - I think warning is still fine since people would be able to filter them out `.Filter.With(TelemetryTypeFilter.On(TelemetryType.Events))`.

**Comment by pim-simons** [comment]
@tomkerkhove That sounds like a good solution.

**Comment by stijnmoreels** [comment]
So, @tomkerkhove , we can close the milestone v1.0.0 after this issue gets closed since #78 is probably not gonna be solved yet.
