### ISSUE TITLE
Changes to correlation information in `DefaultCorrelationInfoAccessor` are not returned

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#159]
**Is your feature request related to a problem? Please describe.**
When using the default correlation info accessor, we set given correlation information multiple times but when retrieving it back; it always provides the initial information, not the last defined on.

**Describe the solution you'd like**
Retrieve the latest defined correlation information.

**Additional context**
We are using Azure Functions and Arcus Observability v1.0 by opting in as following:
```csharp
public override void Configure(IFunctionsHostBuilder builder)
{
   builder.Services.AddHttpClient();
   builder.Services.AddCorrelation();
}
```

However, I doubt that this is unrelated to Azure Functions.

Simple workaround for now is:
```csharp
public class InMemoryCorrelationInfoAccessor : ICorrelationInfoAccessor
{
   private CorrelationInfo _correlationInfo;
   public CorrelationInfo GetCorrelationInfo()
   {
       return _correlationInfo;
   }

   public void SetCorrelationInfo(CorrelationInfo correlationInfo)
   {
       _correlationInfo = correlationInfo;
   }
}

public override void Configure(IFunctionsHostBuilder builder)
{
   builder.Services.AddHttpClient();
   builder.Services.AddCorrelation(provider => new InMemoryCorrelationInfoAccessor());
}
```

**Comment by tomkerkhove** [comment]
This also makes ma wonder why the default implementation is not just like `InMemoryCorrelationInfoAccessor` but I personally don't get what [`AsyncLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netcore-3.1) does.

**Comment by stijnmoreels** [comment]
> This also makes ma wonder why the default implementation is not just like `InMemoryCorrelationInfoAccessor` but I personally don't get what [`AsyncLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netcore-3.1) does.

Storing local value accross asynchronous operations. That's how I saw it. And since we're not sure how this accessor is used; it should be made thread-safe. So, that's why this choice. I'll check.
