### ISSUE TITLE
Provide extension on Serilog to log dependencies

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#16]
Provide extension on Serilog to log dependencies:

Ideas are:
```csharp
_logger.LogHttpDependency(requestMessage, statusCode, duration);
_logger.LogSqlDependency(DatabaseInfo.ServerName, DatabaseInfo.DatabaseName, TableName, operationName, isSuccessful, stopwatch.Elapsed);
```

Extension should allow you to provide contextual information by passing a dictionary, but should not be mandatory.

It should seemlessly integrate with the Azure Application Insight sink and track it as a "Dependency" which is nicely rendered in the application map.

A sample by Tom will be provided as a starting point.

**Comment by stijnmoreels** [comment]
Done?
