### ISSUE TITLE
Update documentation for Serilog & Functions to include dependencies

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.observability#161]
It would be helpful in https://observability.arcus-azure.net/guidance/use-with-dotnet-and-functions.html to include the required packages that are needed for the WriteTo.Console  and the AddSerilog methods

**Comment by SamVanhoutte** [comment]
Required dependencies:
- Serilog.Sinks.Console
- Serilog.Extensions.Logging

**Comment by tomkerkhove** [comment]
Those are more general Serilog packages outside of Arcus but I presume you'd want to have them to provide a full example then?

**Comment by SamVanhoutte** [comment]
I was mostly aiming to have all the using statements included in the doc page, in order to make things easier to "copy/paste"

**Comment by stijnmoreels** [comment]
This was picked up across all repo's via https://github.com/arcus-azure/arcus/issues/107, can you take a look @SamVanhoutte if you agree on the improvement so we can close this?

**Comment by SamVanhoutte** [comment]
Thanks, @stijnmoreels  !!  Appreciated
