### ISSUE TITLE
Remove ASP.NET dependency in `Arcus.Observability.Telemetry.Core`

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#162]
When you have a containerized daemon application (non ASP.NET related), and want to use the Arcus ApplicationInsights sink for serilog, you're required to use an asp.net based container image, since the dependencies in `Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights` require the ASP.NET framework.

There exists an ApplicationInsights package that has no dependency on ASP.NET which can be used in these situations: https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service

It would be nice if Arcus could provide a sink that builds upon this package and can be used in these situations.

**Comment by tomkerkhove** [comment]
It looks like the sink we depend on ([`Serilog.Sinks.ApplicationInsights`](https://www.nuget.org/packages/Serilog.Sinks.ApplicationInsights/)) does not use it so it must be us.

As I feared it is due to our `Arcus.Observability.Telemetry.Core` depending [on ASP.NET](https://github.com/arcus-azure/arcus.observability/blob/master/src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj#L23) for our HTTP logging features so we'll have to split those into separate packages.

**Comment by tomkerkhove** [comment]
We'll introduce a `Arcus.Observability.Telemetry.AspNet` package that contains the LogRequest extensions which require ASP.NET. This allows us to remove the dependency on it in the rest of our packages. Ok for you @fgheysels ?

**Comment by stijnmoreels** [comment]
Used `..AspNetCore` to not confuse with the general ASP.NET dependency.

**Comment by tomkerkhove** [comment]
Given "Core" no longer exists in .NET 5 it might be good to just use AspNet maybe?

Otherwise we have to break it again, but I might be wrong.

Thoughts @fgheysels @stijnmoreels?

**Comment by stijnmoreels** [comment]
Hmm, that's a tricky one 😅, not sure what to do. Maybe indeed just use AspNet, then.

**Comment by fgheysels** [comment]
Naming, one of the most difficult things.

Don't know what to do, as [here](https://devblogs.microsoft.com/aspnet/announcing-asp-net-core-in-net-5/), they're still calling it aspnet.core

**Comment by fgheysels** [comment]
And [here](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five), they're explicitly saying that ASP.NET Core has retained it's name in .NET 5.   So I'd stick with AspNetCore.

**Comment by tomkerkhove** [comment]
Sounds good to me. I'll review the PR asap unless @fgheysels beats me to it.

**Comment by fgheysels** [comment]
Is that a challenge ?

**Comment by tomkerkhove** [comment]
Definately not :D But let's see who gets the 🎖️
