### ISSUE TITLE
Fill Context "OperationName" in request telemetry for Azure Application Insights

### ISSUE THREAD

**Issue by Fabiest** [arcus-azure/arcus.observability#164]
**Is your feature request related to a problem? Please describe.**
Some blades in AppInsights use the field OperationName in the dashboards. Currently this field is not filled by Arcus and there is no way to force it.

**Describe the solution you'd like**
For requests, set the Operation Name to be {Http Verb} {Uri}.

**Describe alternatives you've considered**
Using services.AddApplicationInsightsTelemetry() in startup, but this creates double request entries in AppInsights if used with Arcus.

**Additional context**
![image](https://user-images.githubusercontent.com/43171436/102218770-63030d80-3ed6-11eb-9729-8ab36b7e4474.png)

RED: Web api using both arcus and services.AddApplicationInsightsTelemetry() (in startup, ConfigureServices). As we can see the request shows in double and with different names but the operationName is the same and present.

BLUE: Web api using only services.AddApplicationInsightsTelemetry() (in startup, ConfigureServices). As we can see the request shows both name and operationName.

GREEN: Web api using only arcus. As we can see the request shows name but no operationName.

I have this issue with version 0.2.1 but I can confirm it happens until 1.0.0.
From debugging, I can tell that this is happening because the field telemetryEntry.Context.Operation.Name is never set.

Note: Gillian Verstraete seems to have an example where this is not happening, although it is unclear how and why since the library does not provide this functionality. It might be a good think to check with him how that happens since it might be a possible non-intrusive solution.

**Comment by Fabiest** [comment]
I have not provided my code since it was discussed that this is not an existing behavior, but if needed I can attach the startup and so on of my web api.

**Comment by tomkerkhove** [comment]
Same issue as in https://github.com/arcus-azure/arcus.observability/issues/165, OK for you if I close this one in favor of that one?

**Comment by tomkerkhove** [comment]
Closing since #165 is done
