### ISSUE TITLE
Provide dependency name for all dependencies

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#165]
**Is your feature request related to a problem? Please describe.**
Provide dependency name for all dependencies as it's not always tracked and is listed as `<empty>` as a result in Application Insights.

**Comment by tomkerkhove** [comment]
I'll do a sweep of this and draft a list of expectations.

**Comment by tomkerkhove** [comment]
This needs to be changed in `OperationContextConverter` and related to `telemetryEntry.Context.Operation.Name`.

However, this should be the name of the full operation that is being done, not just a dependency.

**Comment by tomkerkhove** [comment]
https://docs.microsoft.com/en-gb/azure/azure-monitor/app/api-custom-events-metrics#operation-context

**Comment by tomkerkhove** [comment]
This is good doc on how it should work: https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#data-model-for-telemetry-correlation

**Comment by tomkerkhove** [comment]
This is because `telemetryEntry.Context.Operation.Name` is empty:
![image](https://user-images.githubusercontent.com/4345663/128021510-7972791d-8480-412b-bcb4-0f1bb999522e.png)

**Comment by tomkerkhove** [comment]
This dirty test verifies this hypothesis:
```csharp
public void EnrichWithCorrelationInfo<TEntry>(TEntry telemetryEntry) where TEntry : ITelemetry, ISupportProperties
        {
            if (telemetryEntry?.Context?.Operation == null)
            {
                return;
            }

            if (telemetryEntry.Properties.TryGetValue(ContextProperties.Correlation.OperationId, out string operationId))
            {
                telemetryEntry.Context.Operation.Id = operationId;
            }

            if (telemetryEntry.Properties.TryGetValue(ContextProperties.Correlation.OperationParentId, out string operationParentId))
            {
                telemetryEntry.Context.Operation.ParentId = operationParentId;
            }

            if (telemetryEntry is RequestTelemetry f)
            {
                f.Context.Operation.Name = f.Name;
            }

            if (telemetryEntry is DependencyTelemetry d)
            {
                d.Context.Operation.Name = d.Name;
            }
        }
```

**Comment by stijnmoreels** [comment]
@pim-simons will take a first look at this to get a more feeling with the Arcus code. I'll help were necessary.
