### ISSUE TITLE
Improve sample in AppInsights documentation

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#168]
It would be nice to extend the documentation regarding application insights with a more extended code-sample.  Right now, some code is shown on how to log to AppInsights via Serilog, but it is not shown where you could put that code.

I think it would be better for Arcus users to have some more context on that.

**Comment by tomkerkhove** [comment]
Can you elaborate a bit what you're expecting?

**Comment by stijnmoreels** [comment]
Is this something you can/want to pick up, @fgheysels ? Maybe good to have somebody from outside to write this.

**Comment by fgheysels** [comment]
yes, I can do that.   You can assign this to me @stijnmoreels  or @tomkerkhove

**Comment by stijnmoreels** [comment]
Ok great!! Very much appreciated!

**Comment by fgheysels** [comment]
Created a PR in where I've put an extra Q in the Q&A section, however I've made those changes in the 'docs' folder, and not in the preview documentation.  (Which I guess is OK, since afaik, no new functionality is being described).  Should I also update the 'preview' documentation ?  (As I assume that the existing docs will be overwritten by the preview version on a new release ? )

**Comment by stijnmoreels** [comment]
Yes, is ok that you updated the published docs instead of the preview, but you should indeed also update the preview docs as these will like you said be the next published docs.

**Comment by fgheysels** [comment]
> Yes, is ok that you updated the published docs instead of the preview, but you should indeed also update the preview docs as these will like you said be the next published docs.

I'll do that as the last step in this PR (that is, if everything else is good) :)
