### ISSUE TITLE
Provide extension on Serilog to log metrics

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#17]
Provide extension on Serilog to log metrics:

Ideas are:
```csharp
var context = new Dictionary<string, object>
{
    {ContextProperties.Customer, "Contoso"}
};

_logger.LogMetric("Orders Processed", 1, context);
```

Extension should allow you to provide contextual information by passing a dictionary, but should not be mandatory.

It should seemlessly integrate with the Azure Application Insight sink and track it as a "Metric".

A sample by Tom will be provided as a starting point.

**Comment by stijnmoreels** [comment]
Done?
