### ISSUE TITLE
Move to correlation enricher to arcus.observability

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#18]
Move to correlation enricher which already lives in [arcus.webapi](https://github.com/arcus-azure/arcus.webapi/pull/99) to arcus.observability

**Comment by stijnmoreels** [comment]
The one in the web API repo uses the HTTP correlation. That's probably not what we want?

**Comment by tomkerkhove** [comment]
That's what we've discussed before - We'll find a way to make it work for both messaging & web API or provide 2 flavors.

**Comment by tomkerkhove** [comment]
Discussed this again and today, ideally, the HTTP correlation information (or at least the generic info) is available via the dependency container so we can build it upon that.

**Comment by tomkerkhove** [comment]
You could also argue that this should be part of every seperate project since messaging, for example, has a cycle id which needs to be added as well.

Maybe that makes more sense then  @stijnmoreels?

**Comment by stijnmoreels** [comment]
Some more information on where and how this correlation should be available. Parallel requrests with different correlation, places where correlation is needed...

**Comment by tomkerkhove** [comment]
### Background

Let's take as step back and look at what we want to achieve first.

We'd like to provide a consistent approach on how we perform correlation in our applications where we are mainly thinking in terms of Web APIs & workers (messaging).

As part of that effort; we have identified and carved out [`CorrelationInfo`](https://github.com/arcus-azure/arcus.observability/blob/master/src/Arcus.Observability.Correlation/CorrelationInfo.cs) which contains `TransactionId` & `OperationId` which are used by both.

Both Web APIs & workers (messaging) have these concepts while messaging takes it a step further given it also has the concept of `CycleId`.

Our goal is to provide one or more enrichers which will automatically extend all of our telemetry with all of the correlation information that is available

### Challenge

Our challenge is to provide a simple and clean way to achieve this. However, it's not simple because:
- Web API provides [`CorrelationMiddleware`](https://github.com/arcus-azure/arcus.webapi/blob/master/src/Arcus.WebApi.Correlation/CorrelationMiddleware.cs) which registers `CorrelationInfo` as an HTTP feature
- Messaging reads the correlation information inside the message pump and passes it to the message handlers

Both do not register the information in the dependency container so we cannot access it like this.

### Options

1. We move the correlation to dependency container as scoped so that we can write one enricher based on that info.
2. We provide multiple enrichers and make them specific for the application type that need them. No need to add them to the dependency container, but more stuff to add

Without implementing it already, which approach do you think is most feasible and why?

**Comment by stijnmoreels** [comment]
> Without implementing it already, which approach do you think is most feasible and why?
Depedency container seems like the most usable approach. Several other correlation implementations do this also. It would require some kind of "accessor" to retrieve the `CorrelationInfo`.

It would also make the dependent services on correlation more easily developped because you only have to inject this "accessor".
We can't register the correaltion model itself bc we can't "update" the container with registrations (I say can't without using reflection, I looked 😄 ).

So... registering such an accessor interface would be a good approach. A default accessor can be made available that stores this correlation by itself. The Web Api can then implement this interface and use the HTTP request features instead.

I've made a proposal on this approach yesterday: #43

**Comment by tomkerkhove** [comment]
How would you approach it then for messaging where it has an additional field?

**Comment by stijnmoreels** [comment]
> How would you approach it then for messaging where it has an additional field?

Providing an open interface for the correlation accessor (like we did with the message handling, message context) to allow different types of correlations based on the basic one.

**Comment by stijnmoreels** [comment]
I'll keep this open till https://github.com/arcus-azure/arcus.messaging/pull/84 is done.

**Comment by stijnmoreels** [comment]
This is done now, right? No correlation enricher anymore in Web Api.
