### ISSUE TITLE
tracked dependencies do not show up correctly in the Application Insights timeline

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#180]
**Describe the bug**
When I use the Arcus.Observability `LogDependency` extension method on `ILogger`, I've noticed that my tracked dependencies do not show up correctly in the Application Insights timeline:

![image](https://user-images.githubusercontent.com/3605786/109011994-cae18b80-76b1-11eb-9ef3-13c3455fee49.png)
As you can see in the above screenshot, it looks like that my dependency to Timeseries Insights occurred before the initial request to my API was received, which is actually impossible, as my API is calling TSI; so it is not possible that this dependency occurs before the initial request on the API was received.

After some digging around, I have found that it all comes down to the precision of the timestamp that is being logged.  The timestamp of my API request is this:

```
2021-02-24T13:33:26.0349398Z
```

Whereas the timestamp of my tracked TSI dependency is this:

```
2021-02-24T13:33:26Z
```
As you can see, the dependency log's timestamp is only precise to the second, whereas the timestamp of the incoming API request is precise up to the millisecond.
The timestamp of the TSI dependency log will be considered to be 13:33:26.000Z which is then indeed before 13:33:26.0349Z

**Comment by fgheysels** [comment]
It seems that the default format-specifier for DateTime.ToString doesn't take milliseconds into account, so I believe we'll have to use our own format string ?    (fff is used for milliseconds)
However, I don't know in which format this should be written to appinsights: should it be year/month/day ?

**Comment by fgheysels** [comment]
I'm having a look to see if I can fix it.  PR might be incoming

**Comment by tomkerkhove** [comment]
Thanks!

**Comment by tomkerkhove** [comment]
> Is it actually required to write the date/time as a string ?
> https://github.com/arcus-azure/arcus.observability/blob/f609759a102bc99a11a5520d76abc493601b1cf1/src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs#L68

Yes it is for our structured logging in case you don't use Application Insights
