### ISSUE TITLE
handle negative durations in dependency log

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [arcus-azure/arcus.observability#201]
**Is your feature request related to a problem? Please describe.**
When logging a negative dependency duration no exception is thrown and nothing is logged in AI either.

**Describe the solution you'd like**
An exception.

**Describe alternatives you've considered**
Automatically transform to a positive value if negative value is provided. An exception feels more appropriate however.

**Comment by stijnmoreels** [comment]
Thank you! Yes, you're right. This is an additional argument guard we can set in place. Thanks for noticing and notifying!
