### ISSUE TITLE
Scope state is ignored when logging to the Console

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#203]
Consider the following code:

```csharp
 using (_logger.BeginScope(new Dictionary<string, object>()
{
    ["Item"] = "foo",
    ["Error"] = "bar"
}))
{
      _logger.LogError("An error occured!");
}
```

When logging to the console, I'd expect that the additional properties 'item' and 'error' are also visible in the console-logs.  This is however not the case:

![image](https://user-images.githubusercontent.com/3605786/115291543-2c275780-a155-11eb-80de-d9b55142d189.png)

Simple repro-sample:

```csharp
class Program
{
    static async Task Main(string[] args)
    {
         var host = Host.CreateDefaultBuilder(args)
                           .ConfigureLogging(logging => logging.AddConsole())
                           .ConfigureServices(services =>
                           {
                               services.AddHostedService<TestClass>();
                           })
                           .UseSerilog(ConfigureLogger)
                           .UseConsoleLifetime()
                           .Build();

            await host.RunAsync();
    }

    private static void ConfigureLogger(HostBuilderContext context, LoggerConfiguration loggerConfiguration)
    {
            loggerConfiguration.MinimumLevel.Information()
                               .Enrich.FromLogContext()
                               .WriteTo.Console();
    }
}

public class TestClass : BackgroundService
{
    private readonly ILogger<TestClass> _logger;

    public TestClass(ILogger<TestClass> logger)
    {
          _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
            while (stoppingToken.IsCancellationRequested == false)
            {
                using (_logger.BeginScope(new Dictionary<string, object>()
                {
                    ["Item"] = "foo",
                    ["Error"] = "bar"
                }))
               {
                    _logger.LogError("An error occured!");
               }

                await Task.Delay(500);
           }
    }
}
```

**Comment by stijnmoreels** [comment]
Hmm, I don't think this has anything to do with Arcus, as both `.LogError` and .`BeginScope` are concepts outside Arcus. The telemetry context you referring to is only available for Arcus telemetry extensions that actually uses this context. The Serilog extensions doesn't know anything about this.

**Comment by tomkerkhove** [comment]
This is the native console sink for Serilog indeed, but you can change the log output template to surface this, see https://github.com/arcus-azure/arcus.observability/issues/185#issuecomment-792539786 for an example

**Comment by fgheysels** [comment]
Indeed, makes sense.
Also, thanks @tomkerkhove  for pointing me to my other issue which I've absolutely forgotten about :)

The solution is indeed to expand the output-template of the Serilogger.  It is even documented on how to get those extra properties / dimensions into the output.   The [link](https://github.com/serilog/serilog/wiki/Formatting-Output) you've posted in the other issue gives the solution.   

The properties can be visualized by the logger by specifying the `Properties` keyword in the output-template like this:

```csharp
loggerConfiguration.MinimumLevel.Information()
                   .WriteTo.Console(outputTemplate: "[{Timestamp}] {Level} {Message} {Properties:j}{NewLine}");
```

**Comment by tomkerkhove** [comment]
@fgheysels In terms of our templates, would you like or dislike if that was enabled out-of-the-box?

This has cost impact since logs become better but can be nice addition.
