### ISSUE TITLE
Provide support for filtering based on telemetry type with all sinks

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#206]
**Is your feature request related to a problem? Please describe.**
Today, it seems like you can only filter for Azure Application Insights while I would like to do this for console logging.

It might be just me though so just checking but based on the code I think it doesn't work.

**Describe the solution you'd like**
Provide support for filtering based on telemetry type with all sinks, instead of just Azure Application Insights.

![image](https://user-images.githubusercontent.com/4345663/116570321-7903ee80-a90a-11eb-8560-d4edd5a6af31.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by stijnmoreels** [comment]
I'm wondering if it even works at all. It doesn't seem to have any references to tests, sinks.. in the project. 😄

**Comment by tomkerkhove** [comment]
Heh would be nice to fix it in general then :)

Will be easier by using #205 though.
