### ISSUE TITLE
Properties are removed from the log event

### ISSUE THREAD

**Issue by meersschautarnaud** [arcus-azure/arcus.observability#209]
**Describe the bug**
At a customer, we want to write logs to Azure Application Insights and Splunk. When using the Application Insights Serilog sink from Arcus the properties of the log are deleted and therefore not available when writing the logs to Splunk. The `RenderedMessage` will contain a tokenized string instead of the values.

**To Reproduce**
Create a WebApi with the following logger configuration.

```C#
return new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .Enrich.WithVersion()
    .Enrich.WithHttpCorrelationInfo(serviceProvider)
    .WriteTo.Console()
    .WriteTo.AzureApplicationInsights(Configuration[Constants.AppInsightsInstrumentationKey])
    .WriteTo.EventCollector(splunkHost: Configuration[Constants.SplunkHostUrl],
        eventCollectorToken: Configuration[Constants.SplunkToken], host: Configuration[Constants.HostIp],
        index: "main", messageHandler: handler, fields: metaData);
```

**Expected behavior**
The properties are still available when logging to Splunk.

**Additional context**
.NET Core version 3.1

NuGet packages used:
- Serilog.AspNetCore Version="4.0.0"
- Arcus.Observability.Telemetry.Core Version="2.1.0"
- Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights Version="2.1.0"
- Serilog.Sinks.Splunk Version="3.6.0"

**Comment by tomkerkhove** [comment]
Do you have an example of the Splunk output please?

**Comment by meersschautarnaud** [comment]
This is an example of a log in Splunk.
```JSON
{
	"Level": "Information",
	"MessageTemplate": "SQL Dependency {DependencyTargetName} for {DependencyName} for operation {DependencyData} in {DependencyDuration} at {DependencyStartTime} (Successful: {DependencyIsSuccessful} - Context: {@EventDescription})",
	"RenderedMessage": "SQL Dependency {DependencyTargetName} for {DependencyName} for operation {DependencyData} in {DependencyDuration} at {DependencyStartTime} (Successful: {DependencyIsSuccessful} - Context: {@EventDescription})",
	"Properties": {
		"SourceContext": "Codit.Enroll.Configuration.Datalayer.Repositories.MetadataRepository",
		"ActionId": "4634a1be-fdd5-4f9b-962d-1f226599bb98",
		"ActionName": "Codit.EnrollmentService.API.Controllers.EnrollConfigController.GetEnrollConfig (Codit.EnrollmentService.API)",
		"OperationId": "0HM888AB9VP6C:00000001",
		"TransactionId": "a512f735-419d-4d84-a4a5-a44635237fab"
	}
}
```

**Comment by tomkerkhove** [comment]
Is it possible to give the MyGet package for https://github.com/arcus-azure/arcus.observability/pull/207 a try?

**Comment by meersschautarnaud** [comment]
Will do :)

**Comment by meersschautarnaud** [comment]
When testing with the MyGet package for PR 207, I get the following error:
`System.IO.FileNotFoundException: Could not load file or assembly 'Arcus.Observability.Correlation, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

I'm using the following package versions
```xml
<PackageReference Include="Arcus.Observability.Telemetry.AspNetCore" Version="2.1.0" />
<PackageReference Include="Arcus.Observability.Telemetry.Core" Version="20210430.0.0-PR-207" />
<PackageReference Include="Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights" Version="20210430.0.0-PR-207" />
<PackageReference Include="Arcus.WebApi.Logging" Version="1.3.1" />
```

Adding the package `Arcus.Observability.Correlation` with the preview version results in the same error. Reverting package `Arcus.Observability.Telemetry.Core` and `Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights` back to version 2.1.0 resolves the issue.

**Comment by fgheysels** [comment]
I have the same issue with testing the PR 207 preview built in a Web API project.
In another (non Web API project) where I'm using Arcus.Observability, the preview version of Arcus.Observability causes my component to crash because it cannot retrieve / find my secrets anymore.   (I've dropped you guys an e-mail concerning this) :)

**Comment by tomkerkhove** [comment]
@meersschautarnaud in your example above it is because of Arcus.WebApi.Logging but  I have created a discussion for the local issues: https://github.com/arcus-azure/arcus.observability/discussions/211.

**Comment by meersschautarnaud** [comment]
I've tested using version `2.2.0-preview-1` but the result is the same.

Messages sent to Splunk without the sink to Application Insights
```JSON
{"time":"1620301139.302","event":{"Level":"Warning","MessageTemplate":"SQL Dependency {@Dependency}","RenderedMessage":"SQL Dependency DependencyLogEntry { DependencyType: \"Sql\", DependencyName: \"databaseName/tableName\", DependencyData: \"operationName\", TargetName: \"serverName\", ResultCode: null, IsSuccessful: True, StartTime: \"2021-05-06T11:38:57.6505219 +00:00\", Duration: 00:00:01.6405147, Context: [] }","Properties":{"Dependency":{"DependencyType":"Sql","DependencyName":"databaseName/tableName","DependencyData":"operationName","TargetName":"serverName","ResultCode":null,"IsSuccessful":true,"StartTime":"2021-05-06T11:38:57.6505219 +00:00","Duration":"00:00:01.6405147","Context":{},"_typeTag":"DependencyLogEntry"},"SourceContext":"WebAppExample.Controllers.HealthController","ActionId":"cac0e6c4-3fa8-4970-bfda-8c1425169074","ActionName":"WebAppExample.Controllers.HealthController.Get (WebAppExample)","RequestId":"0HM8GGE29QC8U:00000001","RequestPath":"/api/v1/health","SpanId":"|77ab7b30-4b62d2e1ad80f615.","TraceId":"77ab7b30-4b62d2e1ad80f615","ParentId":"","ConnectionId":"0HM8GGE29QC8U","version":"1.0.0","ComponentName":"API","MachineName":"CLT-AMEERSSCHAU","OperationId":"0HM8GGE29QC8U:00000001","TransactionId":"e1489f03-9046-4d07-9b57-d25dc21b956a"}}}
{"time":"1620301139.329","event":{"Level":"Warning","MessageTemplate":"Events {@Event}","RenderedMessage":"Events EventLogEntry { EventName: \"Custom event logged\", Context: [(\"msiSdn\": \"04857982739\")] }","Properties":{"Event":{"EventName":"Custom event logged","Context":{"msiSdn":"04857982739"},"_typeTag":"EventLogEntry"},"SourceContext":"WebAppExample.Controllers.HealthController","ActionId":"cac0e6c4-3fa8-4970-bfda-8c1425169074","ActionName":"WebAppExample.Controllers.HealthController.Get (WebAppExample)","RequestId":"0HM8GGE29QC8U:00000001","RequestPath":"/api/v1/health","SpanId":"|77ab7b30-4b62d2e1ad80f615.","TraceId":"77ab7b30-4b62d2e1ad80f615","ParentId":"","ConnectionId":"0HM8GGE29QC8U","version":"1.0.0","ComponentName":"API","MachineName":"CLT-AMEERSSCHAU","OperationId":"0HM8GGE29QC8U:00000001","TransactionId":"e1489f03-9046-4d07-9b57-d25dc21b956a"}}}
```

Messages sent to Pplunk with the sink to Application Insights
```JSON
{"time":"1620301234.815","event":{"Level":"Warning","MessageTemplate":"SQL Dependency {@Dependency}","RenderedMessage":"SQL Dependency {@Dependency}","Properties":{"SourceContext":"WebAppExample.Controllers.HealthController","ActionId":"9e6ea03f-68e3-4625-b862-1c23b02922b6","ActionName":"WebAppExample.Controllers.HealthController.Get (WebAppExample)","RequestId":"0HM8GGETTJPF6:00000001","RequestPath":"/api/v1/health","SpanId":"0761ade712947340","TraceId":"52d7555bf3889f41a06c08ef0c7134f0","ParentId":"0000000000000000","ConnectionId":"0HM8GGETTJPF6","version":"1.0.0","ComponentName":"API","MachineName":"CLT-AMEERSSCHAU","OperationId":"0HM8GGETTJPF6:00000001","TransactionId":"efd6ea08-9ca6-41b1-a09b-070f3df6c978"}}}
{"time":"1620301234.863","event":{"Level":"Warning","MessageTemplate":"Events {@Event}","RenderedMessage":"Events {@Event}","Properties":{"SourceContext":"WebAppExample.Controllers.HealthController","ActionId":"9e6ea03f-68e3-4625-b862-1c23b02922b6","ActionName":"WebAppExample.Controllers.HealthController.Get (WebAppExample)","RequestId":"0HM8GGETTJPF6:00000001","RequestPath":"/api/v1/health","SpanId":"0761ade712947340","TraceId":"52d7555bf3889f41a06c08ef0c7134f0","ParentId":"0000000000000000","ConnectionId":"0HM8GGETTJPF6","version":"1.0.0","ComponentName":"API","MachineName":"CLT-AMEERSSCHAU","OperationId":"0HM8GGETTJPF6:00000001","TransactionId":"efd6ea08-9ca6-41b1-a09b-070f3df6c978"}}}
```

I've also experienced that the method `LogSqlDepency` requires an operationName even tough there's a constructor without the property.
```C#
using (var measurement = DependencyMeasurement.Start())
{
    _logger.LogSqlDependency("serverName", "databaseName", "tableName", true, measurement);
}

Requires a non-blank name of the SQL operation to track a SQL dependency (Parameter 'operationName')
System.ArgumentException: Requires a non-blank name of the SQL operation to track a SQL dependency (Parameter 'operationName')
```

**Comment by tomkerkhove** [comment]
I'll let @stijnmoreels  check the messages.

> I've also experienced that the method `LogSqlDependency` requires an operationName even tough there's a constructor without the property.
> 
> ```cs
> using (var measurement = DependencyMeasurement.Start())
> {
>     _logger.LogSqlDependency("serverName", "databaseName", "tableName", true, measurement);
> }
> 
> Requires a non-blank name of the SQL operation to track a SQL dependency (Parameter 'operationName')
> System.ArgumentException: Requires a non-blank name of the SQL operation to track a SQL dependency (Parameter 'operationName')
> ```

That is because you did not provide an operation name to the dependency measurement start

**Comment by fgheysels** [comment]
How does your outputtemplate looks like @meersschautarnaud  ?
To get the properties, you'll have to do something like this:

```
loggerConfiguration.WriteTo.Console(outputTemplate: "{Message} {Properties:j}");
```

(Note the Properties. :) ).
I'm trying to get my logs as a JSON format in Log Analytics, but the way the Message is formatted is currently not helping.  Check #205 :)

**Comment by stijnmoreels** [comment]
Our Azure Application Insights Serilog sink does indeed removes all the log properties (like metric name, event name...) and converts this to telemetry instances for AI.
This was probably with the thought in mind that those log events were only useful for AI. But we can/should maybe reconsider this and leave the things open for other sinks.

**Comment by meersschautarnaud** [comment]
> How does your outputtemplate looks like @meersschautarnaud ?
> To get the properties, you'll have to do something like this:
> 
> ```
> loggerConfiguration.WriteTo.Console(outputTemplate: "{Message} {Properties:j}");
> ```
> 
> (Note the Properties. :) ).
> I'm trying to get my logs as a JSON format in Log Analytics, but the way the Message is formatted is currently not helping. Check #205 :)

The JSON is built using a custom [JSON formatter](https://github.com/serilog/serilog-sinks-splunk/blob/1be606219993a710d519db3493c5916c5bfb138c/src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkJsonFormatter.cs) inside the sink for Splunk. When I did the tests I just captured the JSON that was being sent to Splunk.

**Comment by stijnmoreels** [comment]
> > This was probably with the thought in mind that those log events were only useful for AI. But we can/should maybe reconsider this and leave the things open for other sinks.
> 
> I think we should indeed keep all properties or remove only the ones added by the sink if there are any.

@tomkerkhove , this is probably not something that is in line with what we normally do, right?

**Comment by tomkerkhove** [comment]
I don't see a problem with that to be honest. If we use our Application Insights sink, however, we should throw out the ones we need to make decisions unless they add value of course

**Comment by meersschautarnaud** [comment]
Shall I create a PR with a possible solution?

**Comment by tomkerkhove** [comment]
We'll discuss this tomorrow, happy to invite you if you want but don't feel obliged.

**Comment by meersschautarnaud** [comment]
I would like to attend the meeting.

**Comment by stijnmoreels** [comment]
@meersschautarnaud , released a preview of this library: `2.3.0-preview-1`. Let us know if you experience any issues. Thanks!

**Comment by meersschautarnaud** [comment]
@stijnmoreels I did a test with the preview package and it seems to be working as expected :)

**Comment by stijnmoreels** [comment]
> @stijnmoreels I did a test with the preview package and it seems to be working as expected 😃

Great! Thanks for testing. Your change will be included in the upcoming minor release.
