### ISSUE TITLE
Provide application component / role enricher

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#21]
Provide application component / role enricher that will automatically add information concerning the component and the instance name.

- Component name should be defined when configuring the enricher.
- Instance name will either be machine name (when available via https://github.com/serilog/serilog-enrichers-environment) or pod name (when available via https://github.com/arcus-azure/arcus.observability/issues/19)

**Comment by stijnmoreels** [comment]
Yes! And maybe also maybe enrich security events (both success and failures) with a tag;property so we can easily monitor malicious behavior.

**Comment by tomkerkhove** [comment]
I'm not sure I'm understanding your scenario, can you elaborate on it please?

**Comment by stijnmoreels** [comment]
> I'm not sure I'm understanding your scenario, can you elaborate on it please?

Like we enrich the log events with the machine name, context, location, client, ... It would also be beneficial to add a security tag and/or log property. It can be just to tag the event but can also be a level of 'critical/warning/informational'.

When any security event happens (authentication, authorization, input validation, malicious input, additional stuff like firewall/whitelisting, ...) Both the successful and failure could be written with that extra security tag/property.

To oversight the application, it would be very good that these events can be routed. And filtered out. So any malicious activity can be more easily detected.

**Comment by tomkerkhove** [comment]
Would you be open to create an issue for this with the scenario you've mentioned above and some examples please?
