### ISSUE TITLE
Provide comparison between new and old observability extensions

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#217]
**Is your feature request related to a problem? Please describe.**
Provide a comparison between new and old observability extensions after our change to a concrete type.

**Describe the solution you'd like**
We should create a sample application that emits event, metric, logs & dependency information every 5 minutes.

This should be done with 2 unique components, one using the current version and another one with the preview so that we can compare.

Both workloads should be deployed to Kubernetes so that we can verify the outcome in both Azure Application Insights and Log Analytics (through Azure Monitor for Containers).

**Comment by tomkerkhove** [comment]
@fgheysels @stijnmoreels Happy to pick this up, let me know when I can get started!

**Comment by tomkerkhove** [comment]
RG requested

**Comment by stijnmoreels** [comment]
Can be a valuable experiment. I guess once the PR #214 is merged, you can begin.

**Comment by tomkerkhove** [comment]
v2.2 is out so we can skip this since it no longer makes sense
