### ISSUE TITLE
Provide Component Information converter for Application Insights

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#22]
Provide Component Information converter for Application Insights that will use the information from https://github.com/arcus-azure/arcus.observability/issues/21 and configure the cloud context for Application Insights.

This is important so that Application Insights will automatically compose the application map based on that information.

**Comment by tomkerkhove** [comment]
This was done in #40, ok if we close @stijnmoreels?

**Comment by stijnmoreels** [comment]
> This was done in #40, ok if we close @stijnmoreels?

I think it's done yeah, it was tests that were mss maybe?

**Comment by tomkerkhove** [comment]
Ah you are correct! Keeping open for now

**Comment by stijnmoreels** [comment]
Done?
