### ISSUE TITLE
Feature - Security event enrichment with either tag and/or property

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#23]
**What feature would you like to have?**
We enrich the log events with the machine name, context, location, client, ... It would also be beneficial to add a security tag and/or log property. It can be just to tag the event but can also be a level of 'critical/warning/informational'.

When any security event happens (authentication, authorization, input validation, malicious input, additional stuff like firewall/whitelisting, ...) Both the successful and failure could be written with that extra security tag/property.

To oversight the application, it would be very good that these events can be routed. And filtered out. So any malicious activity can be more easily detected.

_Originally posted by @stijnmoreels in https://github.com/arcus-azure/arcus.observability/issues/21#issuecomment-583719302_

**Comment by stijnmoreels** [comment]
An good example is authentication. When the auth for the client fails AND succeeds, and extra security tag/property should be added to the log event so we can route it later.

It can be as simple as:
```csharp
logEvent.AddPropertyIfAbsent("Tag", "Security");
```

But more fine-grained levels, possible with levels of more or less critical can be useful.

**Comment by tomkerkhove** [comment]
Hm, how would you write an enricher that knows when to add the tag and when not?

Isn't it more up to the person logging it to include the tagging as he knows when it's appropriate or not?

**Comment by stijnmoreels** [comment]
Yes, user decides, but we could provide the system. We could even provide a different logging class that adds this (`SecLog.Critical()` for example).
But that's all implementation details.

**Comment by tomkerkhove** [comment]
I'd argue that this is something that is up to the developer to add:
> log.LogInformation("Hello auth ({Tag})", "Security")

We could provide another logger but it should be an extension then.

That said, I don't see how an enricher can help here as it would have to have intelligence to know when to add the property.

**Comment by stijnmoreels** [comment]
> That said, I don't see how an enricher can help here as it would have to have intelligence to know when to add the property.

Yes, when we have a separate logger, a tag should/could be used. But again, that's all implementation details. The point is that with either/both tag/enricher/... or something else... we could easily distinguish security events and that the developer can easily choose whether he/she/x wants to log a security event or not.

**Comment by tomkerkhove** [comment]
That's ok for me, but I think having extensions would be good enough then, shouldn't become too complex.

**Comment by stijnmoreels** [comment]
After consideration... If we would only have an extension to write a security event. How would I write an security for a Application Insights Dependency for example? I would want to add some additional information to the event. So, an enricher would be more in line of this, I guess. Users can then still based on whatever use the enricher or not; without worrying about which extension method to write the event message.

**Comment by tomkerkhove** [comment]
Enrichers purely work on telemetry that has been written already, but how would you know it's a security event?

An extension would write the information concerning the event and an enricher could extend that, if it makes sense and can't be handled in the extension.

Curious about your Application Insights Dependency scenario, what do you have in mind? Because Dependencies are typically not used for that.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackdependency

**Comment by stijnmoreels** [comment]
I was thinking about how like, when a dependent system fails authentication or so, or a HTTP request returns unauthorized, ... but could also be input validation that fails on an external system or so...

**Comment by tomkerkhove** [comment]
That doesn't really make sense given these dependencies will most probably already be measured to cover all scenarios.

**Comment by stijnmoreels** [comment]
> That doesn't really make sense given these dependencies will most probably already be measured to cover all scenarios.

Ok, thanks!

**Comment by stijnmoreels** [comment]
I guess this is done now.
