### ISSUE TITLE
Add special case security event for security alerting

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#233]
**Is your feature request related to a problem? Please describe.**
We already have a way to track security events, which are already being used when calling the secret store, verifying API access keys... But we haven't made a distinction between an alert (read: worth notifying someone).

**Describe the solution you'd like**
It would be great to have an additional `.LogSecurityAlert` that writes a special case event that can be distinguished as an alert event in Application Insights (could be extra key in the telemetry context).

**Comment by stijnmoreels** [comment]
In case of too many events, we could option for a special case metric to track sets of security events.

**Comment by stijnmoreels** [comment]
@gverstraete @meersschautarnaud @fgheysels @pim-simons Would this be worth having? Any suggestions on this?

**Comment by pim-simons** [comment]
First thing that comes to mind is that this might be used in this backgroundjob https://github.com/arcus-azure/arcus.backgroundjobs/tree/master/src/Arcus.BackgroundJobs.AzureActiveDirectory, if a client secret has expired we could use a `LogSecurityAlert` in the logging.

**Comment by stijnmoreels** [comment]
> First thing that comes to mind is that this might be used in this backgroundjob https://github.com/arcus-azure/arcus.backgroundjobs/tree/master/src/Arcus.BackgroundJobs.AzureActiveDirectory, if a client secret has expired we could use a `LogSecurityAlert` in the logging.

Ah yes, but maybe the `LogSecurityEvent` would be enough in that case? As there isn't any additional action to be taken?
Would be a good issue in background jobs, nonetheless.

**Comment by pim-simons** [comment]
Ah yes, I think `LogSecurityEvent` would be enough. 
Not sure about the need for `LogSecurityAlert`, from my point of view the component subscribing to the `LogSecurityEvent` should decide whether or not a notification is needed.

**Comment by stijnmoreels** [comment]
Aha! Yeah, that is a reasonable case. Maybe the 'alert' factor is something we can't 'predict' beforehand.
Ok, I'll add an issue to make sure that we make the `LogEvent` to `LogSecurityEvent` in the background jobs repo. 👍 
https://github.com/arcus-azure/arcus.backgroundjobs/issues/125

**Comment by stijnmoreels** [comment]
> Next to that, what is the difference between LogEvent and LogSecurityEvent ? What will be different in the log when calling one or the other ?

The telemetry context in the case of the security logging is populated with the `EventType = Security`, making it more easily to distinguish security events. This logging type is also built-in in our Arcus security-related components, think about Web API security filters, secret store, and possible background jobs that act upon rotated/expired client secrets...

**Comment by stijnmoreels** [comment]
Ok, I'll close this. Thx all!
