### ISSUE TITLE
Guidance for isolated .net5 Azure Functions

### ISSUE THREAD

**Issue by isaacbromberg** [arcus-azure/arcus.observability#239]
In .net 5 functions in isolated mode, there is HostBuilder instead IFunctionsHostBuilder and it should work with standard asp.net core packages but guidance would be helpful instead of personal experiments with unsure results :)

**Comment by tomkerkhove** [comment]
I don't have experience with the isolated worker but I do have with non-Function workloads.

What issues are you having or what guidance are you seeking?
