### ISSUE TITLE
Support .NET 6 or migrate to .NET 6

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#253]
Since .NET 6 has been released, we should start supporting .NET 6 for the Arcus libraries.

At this moment, we're supporting .NET Core 3.1 and .NET Standard.   Should we stop supporting .NET Standard, as .NET 5, .NET 6 eventually replace .NET Standard in the future ?

(This applies for all Arcus libraries, but it seems that I can't open issues on the arcus-azure organization itself)

**Comment by stijnmoreels** [comment]
Let's close in favor of https://github.com/arcus-azure/arcus/issues/106
