### ISSUE TITLE
Ambiguous calls while using ILoggerExtensions

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.observability#263]
So currently I am having a solution with this setup:

Solution.sln
     SqlProject.csproj
         using Arcus.observability.Telemetry.Sql (2.3.0)
   FunctionProject.csproj
         using SqlProject.csproj
        using Arcus.Observability.Telemetry.Core (2.3.0)

When trying to use the ILoggerExtensions in the FunctionProject I get this exception:
Error	CS0433	The type 'ILoggerExtensions' exists in both 'Arcus.Observability.Telemetry.Core, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' and 'Arcus.Observability.Telemetry.Sql, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null'	Hyperion.Platform.DeviceManagement.Monitor	C:\Dev\Schreder\exedra-device-management-api\src\Hyperion.Platform.DeviceManagement.Monitor\MessageHandlers\MessageLostV1MessageHandler.cs	33	Active

This totally makes sense as the Sql one is indrectly linked.
But how can I fix this? - Just setting the namespace is not enough because it's referring to the same "logical class" as both signatures are the same: https://github.com/arcus-azure/arcus.observability/search?q=ILoggerExtensions

How can I workaround this? - And what was the reasoning for this setup?

Thank you for the feedback!

**Comment by stijnmoreels** [comment]
1. I just tried this setup, but didn't came across this issue. Like Frederik said, the signatures are different. Maybe using the right parameter names can also help you specify directly which overload you want. Let us know!
2. Yes, we have split different dependency tracking in different projects to make sure that we don't include unnecessary packages in the main 'Core' telemetry package. This is done for ASP.NET Core, SQL and IoT dependencies. That doesn't mean that those dependencies can't be tracked only with 'Core', it means that some more tech-specific overloads are located there to help you with your setup (like Frederik realized 😉 ).

**Comment by gverstraete** [comment]
Let me add some more information.
1. I do have the issue when using `LogMetric` since both have these implemented. I don't encounter this at this stage with `LogSqlDependency`
2. You are making a very valid point here! When looking at it today it is pretty odd that it uses `ILoggerExtensions.LogMetric(...)` instead of Logger.LogMetric(...). 

I've modified now from this:
`            ILoggerExtensions.LogMetric(Logger, Metrics.DeviceReconnected, 1.0);`
To this:
`            Logger.LogMetric(Metrics.DeviceReconnected, 1, null);`

And now it does resolve for some reason. Will test a bit further with this and update this thread.
Both implementations implement the LogMetric in their own library, which is causing this exception to occur.
PS: it only works when passing the optional parameters, otherwise I still get the same exception.

**Comment by stijnmoreels** [comment]
Aha! Great to hear. Yes, let us know.

**Comment by fgheysels** [comment]
Conclusion: it's not a great developer experience, so this must be investigated and improved.

**Comment by gverstraete** [comment]
So, it does work like this, but it is indeed not a great experience. 
If I look at it now, using the logger instead of ILoggerExtensions is the better way anyhow... So I could just close it as well. Open for your feedback.

**Comment by fgheysels** [comment]
Is this related to #280 ?

**Comment by gverstraete** [comment]
Yes, it is... This can be closed imo.
