### ISSUE TITLE
Improve documentation by adding a reference to the list of possible ServiceBus clouds/suffixes

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#267]
When logging a ServiceBus request, we have a method which allows to specify the 'ServiceBus' suffix from the ServiceBus namespace of which we receive the request (for instance .servicebus.cloudapi.de).
It would be nice if we could add a reference in our documentation to a list of existing suffixes.  (If this exists in the Microsoft / Azure documentation).

_Originally posted by @fgheysels in https://github.com/arcus-azure/arcus.observability/pull/250#discussion_r788485084_

**Comment by stijnmoreels** [comment]
I think this is a good start: https://docs.microsoft.com/en-us/powershell/module/Az.Accounts/Get-AzEnvironment?view=azps-7.1.0#example-1--getting-all-azure-environments

**Comment by fgheysels** [comment]
This is not mandatory for the 2.4.0 release; I'll add it to 2.5.0
