### ISSUE TITLE
Use of deprecated version of Application Insights Nuget Package

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.observability#271]
As we speak the latest version of the Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights (v2.3.0) is using a very old deprecated version of the Microsoft.ApplicationInsights package (2.13.1)...

That version is long deprecated and it should be upgraded to the latest version.

**Comment by stijnmoreels** [comment]
Yeah, this is definitely something to pick up. Thanks for mentioning it!
@fgheysels , this is not picked up by Renovate bc we only use Renovate in templates. We don't want to force newer versions on consumers, so we use the most compatible version each time. And, when using our own libraries, we use version ranges to be even more compatible with preview releases. 
So, we don't have Renovate here. Maybe there's an option to only inform us of a new version when that version is deprecated.
