### ISSUE TITLE
Remove obsolete `ContextProperties.EventTracking.EventContext`

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#273]
**Is your feature request related to a problem? Please describe.**
We have moved the telemetry context to `ContextProperties.TelemetryContext`, which makes the `ContextProperties.EventTracking.EventContext` obsolete.

**Describe the solution you'd like**
Remove the obsolete context property and related assignments when the log property is added to the Application Insights telemetry.

**Comment by dmallya** [comment]
Hi, could I work on this issue please?

**Comment by stijnmoreels** [comment]
> Hi, could I work on this issue please?

Great that you want to contribute! Super. This issue, however, is for when we release v3.0 which is still a lot in the future for now. See [this list](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aarcus-azure+label%3A%22good+first+issue%22) for any other good first issues to start with Arcus.
Thanks again for your enthusiasm! 🥇
