### ISSUE TITLE
Dependency data in `DependencyMeasurement` is not always used

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#279]
**Describe the bug**
When tracking an dependency, you can use the `DependencyMeasurement` tracking model. This contains a way of specifying a dependency data value, but this value doesn't always corresponds with the dependency data of Application Insights.

**To Reproduce**
Assign dependency data via the `DependencyMeasurement` tracking model (`DependencyMeasurement.Start(dependencyData: "Process"`) and look for the dependency data upon logging. 

**Expected behavior**
Passed-allong dependency data matches.

**Additional context**
 - v2.3.0, current `master`.

**Comment by stijnmoreels** [comment]
In almost all cases, there is already something passed-along to the dependency data (the table name, in case of Azure Table Storage, for example), which raises the question if we should have a dependency data in the measurement after all...

**Comment by fgheysels** [comment]
Actually, I do not see why you want to add additional dependency - data to the measurement.
The measurement should just measure the duration of the dependency call, and that measurement should be used when writing the dependency tracking to the logger.   
At this moment, I do not see a reason why we would have this dependency data in the first place.

On the other hand, is it necessary to remove this right now ?
Also, if we remove this, is there still a reason to differentiate between RequestMeasurement & DependencyMeasurement ?  We could create one type `Measurement` or `DurationMeasurement` for this.

**Comment by stijnmoreels** [comment]
Reusability comes yo mind. If you want to track several dependencies with the same data. 
But otherwise, yeah, something like `TelemetryMeasurement` can be made instead. 😉

I would want to do this change before the release bc otherwise we end up with `RequestMeasurement` that would directly be made obsolete.

**Comment by fgheysels** [comment]
True.

So, how do we agree on this ?
We rename the `RequestMeasurement` to `DurationMeasurement`, and use `DurationMeasurement` also in measuring dependencies , so the `DependencyMeasurement` class, and methods that use `DependencyMeasurement` become obsolete ?

**Comment by stijnmoreels** [comment]
Yes, I think that would be good. It would take a bit of work to mark all those signatures obsolete and create new ones. But yeah, that would be good to do this. 👍

**Comment by stijnmoreels** [comment]
Ok, let's close this in favor of #283  and #284 .
