### ISSUE TITLE
Ambiguous method definition on LogMetric

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#280]
I'm using Arcus.Observability in an Azure Functions project.

I want to make use of the `LogMetric` extension method on ILogger that is defined in Arcus.Observability.
However, when I do that, I get a compiler error regarding an ambiguous method call between
`Microsoft.Extensions.Logging.ILoggerExtensions.LogMetric`
and
`Microsoft.Extensions.Logging.ILoggerExtensions.LogMetric`

This is probably due to the fact that some Arcus libraries are using different versions of Arcus.Observability.
My project references (amongst others):

- Arcus.Observability.Telemetry.AzureFunctions v2.3.0
- Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights v2.3.0 which has a dependency on Arcus.Observability.Telemetry.Core v2.3.0
- Arcus.SEcurity.AzureFunctions v1.6.0
- Arcus.Providers.AzureKeyVault v1.6.0

I can currently work around this by calling the method as a static method instead of calling it as an extension method, but this definitly needs to be tackled.

**Comment by fgheysels** [comment]
Ow, the `LogMetric` method in `LoggerExtensions` is defined in the assembly `Microsoft.Azure.WebJobs.Host`.
Which means that there's not much Arcus can do about it

![image](https://user-images.githubusercontent.com/3605786/151550004-992e0ea3-2ed9-4234-94b2-6042b1f9314e.png)

**Comment by stijnmoreels** [comment]
So this can be closed, then?

**Comment by fgheysels** [comment]
I don't know if we can do anything about. 
Maybe Microsoft should use Arcus.Observability instead, and remove their LogMetric method 😆

**Comment by stijnmoreels** [comment]
> I don't know if we can do anything about. Maybe Microsoft should use Arcus.Observability instead, and remove their LogMetric method 😆

Hihi, 😅 , maybe we should call Tom and do some lobbying 😂.

**Comment by fgheysels** [comment]
Tried that, but @tomkerkhove  suggested that we rename our method instead.

**Comment by tomkerkhove** [comment]
Lol, what I used to do was call `ILoggerExtensions(logger, "name", 1337);` instead

**Comment by tomkerkhove** [comment]
You're only writing one metric though :) `MeasureMetric` or `ReportMetric` are other options.

**Comment by stijnmoreels** [comment]
> You're only writing one metric though :) `MeasureMetric` or `ReportMetric` are other options.

Yeah, 😅, I was thinking, you usually write more than one metric.. we'll see 🙈

**Comment by stijnmoreels** [comment]
> Since all our extension methods start with `Log` (`LogDependency` `LogEvent` .... ) I would also keep that for metrics. In that case, I'd be more in favor for `LogCustomMetric` as suggested earlier ?

Hmm, yeah. Shame, though. Since we also have a `LogEvent` which will log a custom event, but this isn't reflected in the name. Is not really consistent, then. We could opt to also rename the event method, then.

**Comment by stijnmoreels** [comment]
Yeah, ok, let's make it happen!

**Comment by vtermaat** [comment]
> To be honest, I wouldn't mind that we have a method which is called `LogCustomMetric` and anothe rmethod that is just called `LogEvent`.

Oops, I felt LogCustomEvent made more sense. But missed the thumbs-up from Stijn on this final comment.
