### ISSUE TITLE
Introduce package ranges to support all minors under a major

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#330]
**Is your feature request related to a problem? Please describe.**
Currently, we fixate on a single version for a package dependency, which could lead to problems when users want to use Arcus libraries.

**Describe the solution you'd like**
Use package ranges for all minors under a major.

**Comment by fgheysels** [comment]
This issue is related: https://github.com/arcus-azure/arcus/issues/186

**Comment by stijnmoreels** [comment]
Close in favor of https://github.com/arcus-azure/arcus/issues/188
