### ISSUE TITLE
Traces, logs, correlation are lost when using Arcus.Observability in Azure Functions

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#336]
**Describe the bug**

I have a Timer Triggered Azure Function, in where I use Arcus.Observability (and thus also Serilog) to log to Azure Application Insights.

Although there are traces being logged to Application Insights, they're not correlated.   With that , I mean that I cannot get an overview of traces (dependencies, etc... ) that were logged during one Function Invocation.

When I do not use Arcus.Observability and Serilog, everything is nicely linked AND there are things logged that are not logged out-of-the box when using Arcus.

**To Reproduce**

This is how I setup logging using Arcus:

```csharp
internal class Startup : FunctionsStartup
{
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var configuration = builder.GetContext().Configuration;

            builder.ConfigureSecretStore(secretStoreBuilder => AddSecretProviders(secretStoreBuilder, configuration));

            builder.Services.AddLogging(loggingBuilder => ConfigureLogging(loggingBuilder, configuration));
        }

        private static void ConfigureLogging(ILoggingBuilder builder, IConfiguration configuration)
        {
            var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);
            
            var logConfiguration = new LoggerConfiguration()
                                        .MinimumLevel.Is(LogEventLevel.Information)
                                        .Enrich.FromLogContext()                                           
                                        .Enrich.WithComponentName("curated-dsbuilder-plc")
                                        .WriteTo.Console();

            var telemetryKey = configuration.GetValue<string>("APPINSIGHTS_INSTRUMENTATIONKEY");

            if (!String.IsNullOrWhiteSpace(telemetryKey))
            {                
                logConfiguration.WriteTo.AzureApplicationInsights(telemetryKey);
            }

            builder.ClearProvidersExceptFunctionProviders();
            builder.AddSerilog(logConfiguration.CreateLogger());
        }
}
```
When the Function runs, I can find all sort of things in App Insights, but correlation info is missing.   The traces do not contain any `Operation Id` , `Parent Id` header
![image](https://user-images.githubusercontent.com/3605786/154086797-82badef5-0641-444d-acfa-11e714e2cb9d.png)

If I change the function, so that Arcus.Observability and the AppInsights extension is not used for logging, traces are correlated AND I see things being logged that are not logged when using Arcus.Observability:

![image](https://user-images.githubusercontent.com/3605786/154089106-6e07dccb-f02d-447e-8ac7-99e6974aab17.png)

In the screenshot above, you can see that there are traces being logged for getting a token; a (SQL) dependency is logged out of the box to Azure Synapse, ....   These things are not logged out-of-the-box when I use Arcus.Observability (when using Arcus, I make use of an Arcus extension method to log the dependency myself, but when I do not use Arcus, it is done out-of-the box). 
It looks like some traces / dependencies / .... are lost when using Arcus.Observability.   Could this have something to do with configured loglevels ?  (As you can see, the default loglevel that I've configured is Information).

The screenshot above shows what and how is being logged when we setup logging like this:

```csharp
internal class Startup : FunctionsStartup
{
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var configuration = builder.GetContext().Configuration;

            builder.ConfigureSecretStore(secretStoreBuilder => AddSecretProviders(secretStoreBuilder, configuration));
            
            builder.Services.AddLogging();
        }
 }
```
(In my settings I have an `APPINSIGHTS_INSTRUMENTATIONKEY` setting that contains the instrumentation-key of App Insights).

**Expected behavior**
All logs are nicely correlated.
All information that is collected out of the box, must be available in App Insights.

**Comment by stijnmoreels** [comment]
Ok, so to recap: using Arcus/Serilog gives diff results than using Microsoft logging solely.
First off, the `ConfigureLogging` method in the sample is not being used, but that is maybe bc the sample was incomplete. 😅 
I think we need to have a conversation on what where is missing and whether this is a Arcus or Serilog problem, with or without a log level relationship. The HTTP correlation is for example not yet supported in Arcus for Azure Functions, this can maybe also be a reason for this behavior.

**Comment by cahribeiro** [comment]
I am also having this problem. 

```c#
var logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .Enrich.WithComponentName(Constants.ComponentName)
                .Enrich.WithVersion()
                .Enrich.WithHttpCorrelationInfo(builder.Services.BuildServiceProvider())
                .WriteTo.Console()
                .WriteTo.AzureApplicationInsights(instrumentationKey)
                .CreateLogger();
```

![Untitled](https://user-images.githubusercontent.com/41453554/155000200-d8f6985b-5efd-4564-ae28-42221e4b644c.png)

when I run without the "WithHttpCorrelationInfo", it shows correctly.

**Comment by carolinasantos0** [comment]
I am also having this problem. 

```c#
var logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .Enrich.WithComponentName(Constants.ComponentName)
                .Enrich.WithVersion()
                .Enrich.WithHttpCorrelationInfo(builder.Services.BuildServiceProvider())
                .WriteTo.Console()
                .WriteTo.AzureApplicationInsights(instrumentationKey)
                .CreateLogger();
```

![Untitled](https://user-images.githubusercontent.com/41453554/155000200-d8f6985b-5efd-4564-ae28-42221e4b644c.png)

when I run without the "WithHttpCorrelationInfo", it shows correctly.

**Comment by fgheysels** [comment]
> Ok, so to recap: using Arcus/Serilog gives diff results than using Microsoft logging solely. First off, the `ConfigureLogging` method in the sample is not being used, but that is maybe bc the sample was incomplete. 😅 I think we need to have a conversation on what where is missing and whether this is a Arcus or Serilog problem, with or without a log level relationship. The HTTP correlation is for example not yet supported in Arcus for Azure Functions, this can maybe also be a reason for this behavior.

't Was indeed a mistake in the sample.  I corrected it.

**Comment by fgheysels** [comment]
@carolinasantos0  What version of Arcus.Observability are you using ?

**Comment by carolinasantos0** [comment]
@fgheysels  also 2.3.0.
Yes, same here. I'm using azure functions too

**Comment by stijnmoreels** [comment]
> @fgheysels : As you can see, I'm not even using ´WithHttpCorrelationInfo`.

I'm wondering, if this is a problem of linking/correlation, and we don't use Arcus. Again, HTTP correlation in logging is not yet supported with Arcus. Then, I'm wondering if this is something to do with Arcus, and rather Serilog and/or log levels. Maybe a dedicated meeting should be planned for this.

**Comment by stijnmoreels** [comment]
@carolinasantos0 , the way you're using the `IServiceProvider` and the Serilog HTTP correlation, is not correct. Building a dedicated `IServiceProvider` with `.BuildServiceProvider` is not the solution to make Arcus support HTTP correlation in a Serilog environment. We don't support HTTP correlation in an Azure Functions environment.

**Comment by fgheysels** [comment]
I think this will indeed call for a dedicated meeting / more investigation.

I can already say that:

- I'm experiencing this in an Azure Function that is timer-triggered, running .NET 6 on Functions Runtime ~4
- I'm also seeing the same behavior in multiple .NET Core 3.1 Azure Functions (Azure Functions runtime ~3).  Some of them are timer-triggered, others are eventhub, servicebus or blob triggered

It is hard to say whether this is Serilog or Arcus related.

**Comment by fgheysels** [comment]
It looks like it's more working as expected if I do not call the `ClearProvidersExceptFunctionProviders()` method on the `ILoggingBuilder`.

**Comment by fgheysels** [comment]
When looking at the `ClearProvidersExceptionFunctionProviders`, the code looks a bit dangerous.  This method was introduced because of custom dimensions that would dissapear, but we'll investigate this further.

**Comment by fgheysels** [comment]
I've done some further investigation:

- It seems that the `ClearProvidersExceptFunctionProviders` method doesn't remove anything.  The only `ILoggerProvider` instances that are registered, are the 2 that should not be removed (in a default setup).
- It looks like this method would also not function correctly:  Should there be additional `ILoggerProvider` instances registered, there will only be one instance removed (the first one encountered), hence the `break` statement that forces exitting the loop
- Not using `ClearProvidersExceptFunctionProviders` makes sure that logging to App Insights for your Function App is now done correctly.  Which is actually weird, as the `ClearProviders...` method does actually nothing except looping over the `Services` collection.   (Maybe that causes some side-effect ? )
- Custom dimensions are still correctly registered in App Insights when we're not calling this method when setting up logging

Therefore, I've decided to mark this method as obsolete.   It can be removed in a later phase.  (Note that this also has an effect on the `Arcus.Observability.Telemetry.AzureFunctions` package, as this extension method is the only thing that exists in this package.

**Comment by fgheysels** [comment]
I have now noticed that traces are written twice to application insights.  Needs to be investigated further.

**Comment by stijnmoreels** [comment]
> I have now noticed that traces are written twice to application insights from within my FunctionApp. Needs to be investigated further.

Hehe, that's strange. 😅 Maybe something with sinks that are registered twice and/or Serilog+Microsoft logging and/or methods that are called twice?

**Comment by stijnmoreels** [comment]
Ok, wauw, that's kinda strange 🤔 . It's a good thing you found it!

**Comment by fgheysels** [comment]
I'll close this issue, as I've created another issue for the duplicated traces (and other strange things).
https://github.com/arcus-azure/arcus.observability/issues/359
