### ISSUE TITLE
Improve DefaultCorrelationInfoAccessor tests

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#344]
The `DefaultCorrelationInfoAccessorTests` is currently calling a method which has been defined as `async` but the method is not awaited.  This is done to test the issue that was reported in #159 

However, imho, calling this 'async' method will have not much effect, as it will be called synchronously (see also the compiler warning).

Additionally, this test is calling into deprecated properties of the  `DefaultCorrelationInfoAccessor` (It is used as a singleton, but the `Instance` property is marked as obsolete.   The deprecation-message says that we should create a new instance of the `DefaultCorrelationInfoAccessor` instead.

This test must be reviewed to:
- no longer use the deprecated singleton functionality, or at least, we should add a test which uses the recommended approach
- we must verify if the test like it is now makes sense.

**Comment by stijnmoreels** [comment]
I remember changing the async method to returning a `Task` and it didn't test the issue. So the way it was written was really to verify if we correctly used the `AsyncLocal` type correctly. We could add a `Task.Delay` to make it more 'async' and maybe more understandable for testers, but the way the test was written is definitely the way it's supposed to test it. This is I think more about task context switching, which was how the `AsyncLocal` type acted differently.

In any case, this is indeed obsolete functionality, so I would think we should not be too fixated on this 😅 .

**Comment by stijnmoreels** [comment]
Low-prio.
