### ISSUE TITLE
Replace Microsoft.Azure.ApplicationInsights.Query dependency

### ISSUE THREAD

**Issue by scottaddie** [arcus-azure/arcus.observability#355]
Last week, the Azure SDK team deprecated Microsoft.Azure.ApplicationInsights.Query in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). Please make plans to migrate. Migration guidance has been provided at https://aka.ms/azsdk/net/migrate/ai-monitor-query.

Per [this announcement](https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/), support for this deprecated package ends on March 31, 2023.

**Comment by stijnmoreels** [comment]
Aha! Thx Scott! ❤️ 
We should indeed make sure that we update this. Thx for mentioning!

**Comment by stijnmoreels** [comment]
Seems like the new package is a serious step down on the things we required from the API on Application Insights. Will require a lot of custom code to integrate this again in a easy-working test approach.

**Comment by scottaddie** [comment]
@stijnmoreels Which specific features are missing or lacking from Azure.Monitor.Query? Any feedback you can provide will help me better understand how to improve the developer experience.

**Comment by stijnmoreels** [comment]
> @stijnmoreels Which specific features are missing or lacking from Azure.Monitor.Query? Any feedback you can provide will help me better understand how to improve the developer experience.

@scottaddie , the previous versions where using typed responses from the Application Insights API. As in: the response was different when calling dependencies, requests... while now it returns a generic table. This is probably due to the fact that you now can pass in your own Kusto query and the implementation doesn't now what types to return, but this greatly reduces the user experience as (not like before) every column now has to be cast the necessary type. Making it very unstable, I think. That we now can access the API with Azure.Identity, that, I think is an improvement on simplicity.

**Comment by scottaddie** [comment]
@stijnmoreels Thank you for the feedback. Can you please [create an issue](https://github.com/Azure/azure-sdk-for-net/issues/new/choose) with the specific things you'd like to see in the Azure Monitor Query library? A code sample of what you've described above would be very helpful.

**Comment by stijnmoreels** [comment]
> Last week, the Azure SDK team deprecated Microsoft.Azure.ApplicationInsights.Query in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). Please make plans to migrate. Migration guidance has been provided at https://aka.ms/azsdk/net/migrate/ai-monitor-query.
> 
> Per [this announcement](https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/), support for this deprecated package ends on March 31, 2023.

Done in https://github.com/Azure/azure-sdk-for-net/issues/28254

**Comment by stijnmoreels** [comment]
Current new version of the monitor query is not dev-friendly enough for now to be upgrade towards it.
Closing for now.
