### ISSUE TITLE
Remove the deprecated `LogServiceBus...Dependency` extensions

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#406]
**Is your feature request related to a problem? Please describe.**
Previous.y, we used the `DependencyMeasurement` to track Azure Service Bus dependencies and were not using the namespace of the entity.

**Describe the solution you'd like**
Remove the deprecated `LogServiceBus...Dependency` extensions in the `Arcus.Observability.Telemetry.Core` project that:
- are using the `DependencyMeasurement` type
- are missing the Azure Serivice Bus namespace endpoint

This is needed for the `LogServiceBusQueueDependency`, `LogServiceBusTopicDependency` and `LogServiceBusDependency` extensions.

**Comment by vtermaat** [comment]
picking this up

**Comment by vtermaat** [comment]
Is this an example of an obsolete method that should NOT be removed?
As it uses DurationMeasurement.

https://github.com/arcus-azure/arcus.observability/blob/1a3900b25980fc9b46230893dc2d5f854ee58bed/src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs#L50

**Comment by stijnmoreels** [comment]
> > * are using the `DependencyMeasurement` type
> > * are missing the Azure Serivice Bus namespace endpoint
> 
> Is this an example of an obsolete method that should NOT be removed? As it uses DurationMeasurement.
> 
> https://github.com/arcus-azure/arcus.observability/blob/1a3900b25980fc9b46230893dc2d5f854ee58bed/src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs#L50

No, those can also be removed, as they are already made deprecated in v2.5. So, its fine.

**Comment by stijnmoreels** [comment]
Actually, any extension here that don't have an Azure Service Bus endpoint namespace, can be removed, along side extensions that still uses the `DependencyMeasurement`.
