### ISSUE TITLE
Remove deprecated `LogTableStorageDependency` extensions

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#407]
**Is your feature request related to a problem? Please describe.**
Previously, we used the `DependencyMeasurement` to track dependencies but we have changed that to the `DurationMeasurement`.

**Describe the solution you'd like**
Remove the `LogTableStorageDependency` extension in the `Arcus.Observability.Telemetry.Core` project that still uses the `DependencyMeasurement`.

**Comment by vtermaat** [comment]
picking this up
