### ISSUE TITLE
Using Arcus & Serilog in Functions documentation is lacking some information

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#440]
In [this](https://observability.arcus-azure.net/Guidance/use-with-dotnet-and-functions) documentation-page, it is mentionned that you need to install the package `Arcus.Observability.Telemetry.AzureFunctions` to get the sample working.
That is actually not enough.  You also need:

- Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights
- Arcus.Observability.Telemetry.Core (indirectly referenced by the ApplicationInsights package)
- Arcus.Observability.Telemetry.Serilog.Enrichers (indirectly referenced by the ApplicationInsights package)
- Serilog.Sinks.Console
- Serilog.Extensions.Logging

It would be good to mention this in the documentation

**Comment by stijnmoreels** [comment]
We mention to 'follow Serilog' instructions, so maybe that's enough. But indeed the ApplicationInsights package is missing here. Maybe this list can be added here. 👍
