### ISSUE TITLE
InvalidOperation is thrown when calling RemoveMicrosoftApplicationInsightsLoggerProvider

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#441]
**Describe the bug**
I've setup Arcus Observability logging in an Azure Function as described here.

However, when I run the project (locally), this exception is thrown:

![image](https://user-images.githubusercontent.com/3605786/179754835-6bd1f280-2a14-4f3b-b9c7-ac794409681a.png)

I believe we should not throw an exception when the ApplicationInsightsLoggerProvider is not present when we call this method.
(As mentionned [here](https://github.com/arcus-azure/arcus.observability/pull/374#discussion_r879143002)).

**Comment by fgheysels** [comment]
It is a new Function, but I haven't created it using the Arcus template.
Target Framework is .NET 6

**Comment by stijnmoreels** [comment]
> It is a new Function, but I haven't created it using the Arcus template. Target Framework is .NET 6

Isolated Azure Functions are also not required to use this.

**Comment by fgheysels** [comment]
Weird, I cannot reproduce this anymore atm.  But I have another issue ...

**Comment by stijnmoreels** [comment]
Aha, this is also not needed anymore for the newest Azure Functions SDK as it seems that the Microsoft `ILoggerProvider` that write to Application Insights is no longer there. 🤔
