### ISSUE TITLE
Logs / traces are duplicated when using Arcus.Observability with Azure Functions

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#453]
**Describe the bug**
I have an Azure Function where I make use of Arcus.Observability to write logs to App Insights.
My setup looks like this:

```csharp
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var logger = CreateSeriLogLogger(builder);

            builder.Services.AddLogging(loggingBuilder =>
            {
                loggingBuilder
                             //.RemoveMicrosoftApplicationInsightsLoggerProvider()
                              .AddSerilog(logger);
            });
        }

        private Serilog.Core.Logger CreateSeriLogLogger(IFunctionsHostBuilder builder)
        {
            var config = builder.GetContext().Configuration;

            var instrumentationKey = config.GetValue<string>("APPINSIGHTS_INSTRUMENTATIONKEY");

            var loggerConfiguration = new LoggerConfiguration()
                .MinimumLevel.Information()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .Enrich.WithComponentName("APIM EventsProcessor")
                .Enrich.WithVersion()
                .WriteTo.Console();

            if(!String.IsNullOrWhiteSpace(instrumentationKey)) 
            { 
                loggerConfiguration.WriteTo.AzureApplicationInsightsWithInstrumentationKey(instrumentationKey);
            }
                
            var logger = loggerConfiguration.CreateLogger();

            return logger;
        }
```

Every call to `LogInformation` etc... appears twice in Application Insights.
As you can see, in the above snippet the call to `RemoveMicrosoftApplicationInsightsLoggerProvider` is commented out.

When I do use that method, nothing is written to Application Insights.

I'm using Arcus.Observability.Telemetry.AzureFunctions v2.5.0 and Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights v2.5.0

**Comment by stijnmoreels** [comment]
Oh, something that maybe was looked over: did the `local.appsettings.json` or `host.json` have any logging settings? As these could also conflict in what we're trying to do here.

**Comment by fgheysels** [comment]
My host.json has some logging settings, but looks like merely how sampling must be applied:

```json
{
  "version": "2.0",
  "applicationInsights": {
    "samplingSettings": {
      "isEnabled": true,
      "excludedTypes": "Request"
    }
  }
}
```

**Comment by stijnmoreels** [comment]
Are we also sure that the endpoint/trigger isn't called twice or that the code is run twice?
This won't be something related to our sink, I think, as this is only happening in Azure Functions (not the first time). I imagine it must be some place or obscure stuff that makes this thing behave as it does. Maybe check with our project templates to look for differences?

**Comment by fgheysels** [comment]
Function is not invoked twice.
This is not only a very annoying thing, but it also impacts Azure consumption costs, as we're logging everything twice, this means the amount of data ingested in appinsights/log analytics is also doubled, so we're paying almost twice as much as well.

**Comment by stijnmoreels** [comment]
Maybe related to these?
https://github.com/Azure/azure-functions-host/issues/1431
https://github.com/Azure/azure-functions-host/issues/1627

**Comment by fgheysels** [comment]
I have now made sure that my code looks (almost) exactly the same as what we have in the Http Triggered Azure Function Arcus template.  The only difference is that I write to AppInsights using the instrumentation-key instead of the connectionstring, and nothing ends up in Application Insights.  However, I'm sure that the Function is running as I can see the result of the Function.

**Comment by fgheysels** [comment]
I'm going to open a new issue. :)
