### ISSUE TITLE
Azure Function is not logging requests when using Arcus Observability

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#454]
I have an Azure Function (EventGrid triggered) which uses Arcus.Observability for logging, and I send logs to Application Insights
I haven't created the function from an Arcus Template, but I've made sure that I use the same code as the code generated via ARcus Templates.

My Function runs as expected, but I cannot see the requests coming in Application Insights.  However, if I search in Application Insights, I can find the traces that my Function is producing.  They're just not linked to a request, and this also makes sure that I cannot correlate all traces that belong to the same invocation.

This is how the Startup.cs looks like:

```csharp
    public class Startup : FunctionsStartup
    {
        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            base.ConfigureAppConfiguration(builder);

            builder.ConfigurationBuilder.AddEnvironmentVariables();
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.AddHttpCorrelation();

            var loggerConfiguration = CreateLoggerConfiguration(builder);

            builder.Services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.RemoveMicrosoftApplicationInsightsLoggerProvider()
                              .AddSerilog(loggerConfiguration.CreateLogger(), dispose: true);
            });
        }

        private static LoggerConfiguration CreateLoggerConfiguration(IFunctionsHostBuilder builder)
        {
            var config = builder.GetContext().Configuration;

            var instrumentationKey = config.GetValue<string>("APPINSIGHTS_INSTRUMENTATIONKEY");

            var loggerConfiguration = new LoggerConfiguration()
                .MinimumLevel.Information()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .Enrich.WithComponentName("APIM EventsProcessor")
                .Enrich.WithVersion()
                .WriteTo.Console();

            if(!String.IsNullOrWhiteSpace(instrumentationKey)) 
            { 
                loggerConfiguration.WriteTo.AzureApplicationInsightsWithInstrumentationKey(instrumentationKey);
            }

            return loggerConfiguration;
        }
    }
```

The host.json looks like this:

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  }
}
```

**Comment by stijnmoreels** [comment]
HTTP request tracking in in-process Azure Functions don't happen in the startup code, (due to not-available middleware), these are tracked by yourself as shown in the HTTP trigger template: https://github.com/arcus-azure/arcus.templates/blob/c95da54dbc3822a202ef6ea5485477963ce0234e/src/Arcus.Templates.AzureFunctions.Http/OrderFunction.cs#L106

**Comment by fgheysels** [comment]
Thanks for pointing that out.

However, if that is the case, I wonder why we would be using Arcus.Observability in Azure Functions, since we have this behaviour out of the box when not using Arcus.Observability....

**Comment by stijnmoreels** [comment]
> Thanks for pointing that out.

👍 
 
> However, if that is the case, I wonder why we would be using Arcus.Observability in Azure Functions, since we have this behaviour out of the box when not using Arcus.Observability....

Observability also make sure that we enrich with component name, version, and provides contextual information on all telemetry that is send to Application Insights. This full control over what is send when to Application Insights is the big plus here.

**Comment by stijnmoreels** [comment]
Also, the Observability-way allows you to ignore certain routes, and provide request/response bodies if needed, something that is not configurable directly as it is hidden away.

**Comment by stijnmoreels** [comment]
We can close this?

**Comment by fgheysels** [comment]
Yes.  For the moment, I've removed Arcus Observability from my Function.
