### ISSUE TITLE
Provide capability to easily measure dependency duration

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#46]
Provide capability to easily measure dependency duration.

Today we support:
```csharp
var durationMeasurement = new Stopwatch();
var startTime = DateTimeOffset.UtcNow;
durationMeasurement.Start();

var response = await httpClient.SendAsync(request);

_logger.LogHttpDependency(request, response.StatusCode, startTime, durationMeasurement.Elapsed, context: context);
```

## Proposal
We should make it easier by introducing `DependencyMeasurement` which provides a `Start()` and `Start("My Operation")`.

It would allow us to do this:
```csharp
using(var dependencyMeasurement = DependencyMeasurement.Start())
{
   var response = await httpClient.SendAsync(request);

   _logger.LogHttpDependency(request, response.StatusCode, dependencyMeasurement.StartTime, dependencyMeasurement.Elapsed, context: context);
}
```

With passing the operation name, it can be used for dependencies such as SQL.

We can then also provide an *overload* (we should not enforce it) to pass the measurement as a whole:
```csharp
_logger.LogHttpDependency(request, response.StatusCode, dependencyMeasurement, context: context);
```

**Comment by stijnmoreels** [comment]
Something simulair for the logging of requests could be used.
Maybe then call it `Measurement` instead?

**Comment by stijnmoreels** [comment]
+ maybe we could send the measurement itself with the logging instead of separatly start/duration?

**Comment by tomkerkhove** [comment]
> * maybe we could send the measurement itself with the logging instead of separatly start/duration?

See above:
> We can then also provide an overload (we should not enforce it) to pass the measurement as a whole:

We should not force people to use it, but provide them the tools

> Something simulair for the logging of requests could be used.
> Maybe then call it `Measurement` instead?

Let's start with dependencies first and then look at requests to prevent to overcomplicate things.
