### ISSUE TITLE
Provide capability to track an Azure IoT Hub dependency

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#54]
**Is your feature request related to a problem? Please describe.**
Provide capability to track an Azure IoT Hub dependency.

**Describe the solution you'd like**
We should provide a `LogIoTHubDependency` overload for `ILogger` which is optimized for Azure IoT Hub and correctly generates the [Azure Application Insights App Map](https://docs.microsoft.com/en-gb/azure/azure-monitor/app/app-map).

**Describe alternatives you've considered**
None

**Additional context**
Dependency type should be used from [official SDK](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/DependencyCollector/Implementation/RemoteDependencyConstants.cs).

**Comment by stijnmoreels** [comment]
Reopend for docs.

**Comment by tomkerkhove** [comment]
Documented so can be closed - Right?
https://observability.arcus-azure.net/features/writing-different-telemetry-types#measuring-azure-iot-hub-dependencies
