### ISSUE TITLE
Provide capability to track an Azure Service Bus dependency

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#58]
**Is your feature request related to a problem? Please describe.**
Provide capability to track an Azure Service Bus dependency.

**Describe the solution you'd like**
We should provide a `LogServiceBusDependency` overload for `ILogger` which is optimized for Azure Service Bus and correctly generates the [Azure Application Insights App Map](https://docs.microsoft.com/en-gb/azure/azure-monitor/app/app-map).

It should support both queues and topics.

**Describe alternatives you've considered**
None

**Additional context**
Dependency type should be used from [official SDK](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/RemoteDependencyConstants.cs).

**Comment by stijnmoreels** [comment]
On what available properties do you think this overload should have?
- Entity type queue/topic
- Entity Name
- ...?

**Comment by tomkerkhove** [comment]
Let's get it working first and then see what we need :)

**Comment by stijnmoreels** [comment]
Tried something to also investigate in #71 but nothing so far 😭 .

**Comment by stijnmoreels** [comment]
Done?
