### ISSUE TITLE
Provide capability to track an Azure Event Hubs dependency

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#59]
**Is your feature request related to a problem? Please describe.**
Provide capability to track an Azure Event Hubs dependency.

**Describe the solution you'd like**
We should provide a `LogEventHubsDependency` overload for `ILogger` which is optimized for Azure Event Hubs Storage and correctly generates the [Azure Application Insights App Map](https://docs.microsoft.com/en-gb/azure/azure-monitor/app/app-map).

**Describe alternatives you've considered**
None

**Additional context**
Dependency type should be used from [official SDK](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/DependencyCollector/Implementation/RemoteDependencyConstants.cs).

**Comment by stijnmoreels** [comment]
Reopened for docs.
