### ISSUE TITLE
Provide integration tests that write to Azure Application Insights via Serilog

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#61]
**Is your feature request related to a problem? Please describe.**
Provide integration tests that write to Azure Application Insights via Serilog.

**Describe the solution you'd like**
Provide integration tests that write to Azure Application Insights via Serilog.

Every test should include following context:
- Generate & include correlation information
- Name of test
- Name of test run (if possible at all but not a must)

This would allow us to use it to lookup the written telemetry during verification if we want to.

**Additional context**
This allows us to manually verify the information in Azure Application Insights before shipping, for example is the app map correctly rendered?

**Comment by tomkerkhove** [comment]
Are you up for checking if we can pull the data back to assert on it @stijnmoreels?

**Comment by stijnmoreels** [comment]
> Are you up for checking if we can pull the data back to assert on it @stijnmoreels?

I did try something using a private preview package. I can see if I can find some way, but should that be blocking for the release?😳

**Comment by stijnmoreels** [comment]
Ok, I think I figured it out.

**Comment by tomkerkhove** [comment]
Not perse but just tracking it as part of this milestone - I'll kick it off while you're working on this; ok?

**Comment by stijnmoreels** [comment]
Yeah, you can proceed with the release if you think everything is in place; I'll continue with the testing.
