### ISSUE TITLE
Provide integration tests for our enrichers

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#67]
**Is your feature request related to a problem? Please describe.**
Provide integration tests for our enrichers so that we can verify them as well.

**Comment by stijnmoreels** [comment]
How would this work? Can you give some guidance in how these tests are gonna be different from the unit tests we have?

**Comment by tomkerkhove** [comment]
That they effectively write to application insights to verify that the cloud context is set for exampel

**Comment by stijnmoreels** [comment]
So write a log message, enrichment, and leaving the assertion open for now?

**Comment by tomkerkhove** [comment]
Yes

**Comment by tomkerkhove** [comment]
Once that is done, feel free to investigate pulling the info back in the tests

**Comment by stijnmoreels** [comment]
Both this and other issue is still open for the v0.1.0 milestone, but that's okay I guess? They're only open bc there's not yet an automatic assertion in place.😬

**Comment by stijnmoreels** [comment]
Meaning, are we done with v0.1.0 milestone?

**Comment by tomkerkhove** [comment]
Let's close this in favor of #61
