### ISSUE TITLE
Verify custom dependency & request integration tests

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#71]
Verify custom dependency & request integration tests.

Follow-up of https://github.com/arcus-azure/arcus.observability/pull/62 & https://github.com/arcus-azure/arcus.observability/pull/64

**Comment by stijnmoreels** [comment]
Why we can't see the custom dependencies is still something I don't understand. Is there something wrong with the names of the log properties? Bc there's no exception, no wrong message template, no spaces in dependency type... And I'm sure I should see it on the application map, right?

**Comment by stijnmoreels** [comment]
Maybe some required properties here 🤔 but then the fault is hidden somewhere. I'll look into that...

**Comment by tomkerkhove** [comment]
> And I'm sure I should see it on the application map, right?

You should also see them if you go to `Search` and filter on `Event Type: Dependency`:
![image](https://user-images.githubusercontent.com/4345663/78770564-063a7500-798f-11ea-9d7c-493694009c92.png)

If you go to the App Map, make sure to increase the time period in which you'd expect them to show up:
![image](https://user-images.githubusercontent.com/4345663/78770639-21a58000-798f-11ea-86a0-f8d11718fabb.png)

Here you see why it's important to use the correct dependency type as they use it to visualize the dependency with (ie SQL & HTTP)

You are probably asking because of the custom dependency tests then or?

**Comment by tomkerkhove** [comment]
You can apply filters as well in search:
![image](https://user-images.githubusercontent.com/4345663/78770903-92e53300-798f-11ea-84c1-3d5a67c62db7.png)

**Comment by stijnmoreels** [comment]
Yes, asking about the custom dependency tests. Nothing to show in Application Insights 😭 .

**Comment by stijnmoreels** [comment]
Made sure every property was filled out so I don't miss required properties.
