### ISSUE TITLE
Find out why dependency traces in tests contain EventDescription

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#83]
Find out why dependency traces in tests contain EventDescription:
https://user-images.githubusercontent.com/9039753/79344966-cc3e1580-7f30-11ea-9271-2277ba30b174.png

I thought it was passed here: https://github.com/arcus-azure/arcus.observability/blob/master/src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs#L162

But looks like it's coming from https://github.com/arcus-azure/arcus.observability/blob/e8872f93b4d0b30691e14e71a0732caed69d0675/src/Arcus.Observability.Telemetry.Core/ContextProperties.cs#L32

**Comment by stijnmoreels** [comment]
Not sure what you want or mean by this? Renaming? Removing from custom properties?

**Comment by tomkerkhove** [comment]
I'm wondering why it's their and using that name? `EventDescription` in the context of a dependency makes no sense and my gut says this is probably there for other telemetry types as well or not?

**Comment by stijnmoreels** [comment]
Yes, it was there all along, as a way to set the context on all telemetry types.

**Comment by tomkerkhove** [comment]
Frankly, I think the field should be removed for all telemetry types since they are already reported individually:
![image](https://user-images.githubusercontent.com/4345663/79435256-b4699e80-7fcf-11ea-86ea-f00aa0bb5ea7.png)

**Comment by stijnmoreels** [comment]
Yes, was indeed something I asked. Ok, let's do that.

**Comment by tomkerkhove** [comment]
Awesome, thanks!
