### ISSUE TITLE
Provide more context on where to use the different telemetry types

### ISSUE THREAD

**Issue by wseye** [arcus-azure/arcus.observability#91]
Documentation could be improved by providing more context on where to use the different [telemetry types](https://observability.arcus-azure.net/features/writing-different-telemetry-types)

**Comment by tomkerkhove** [comment]
Is this only for different telemetry types or in general?

**Comment by tomkerkhove** [comment]
Is this useful @wseye - https://www.codit.eu/blog/announcing-arcus-observability/

**Comment by tomkerkhove** [comment]
Feel free to re-open with more information how we can help.

Closing for now.
