### ISSUE TITLE
provide more information on why/when you would need correlation

### ISSUE THREAD

**Issue by wseye** [arcus-azure/arcus.observability#92]
The [documentation ](https://observability.arcus-azure.net/features/correlation) explains the use of correlation very well, but it's not clear to me when or why I would need that.

**Comment by tomkerkhove** [comment]
Does this help https://www.codit.eu/blog/announcing-arcus-observability/? I can check how we can incorporate it.

**Comment by tomkerkhove** [comment]
Feel free to re-open with more information how we can help.

Closing for now.
