### ISSUE TITLE
Add dedicated integration test for correlation enricher

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#93]
**What feature would you want?**
Having a dedicated integration test for the correlation enricher to verify it works might be interesting.

_Originally posted by @tomkerkhove in https://github.com/arcus-azure/arcus.observability/pull/85_

**Comment by stijnmoreels** [comment]
This will probably not work in with the current setup bc the Azure preview library doesn't support this yet AFAIK.

**Comment by tomkerkhove** [comment]
Movingfor now then!

**Comment by stijnmoreels** [comment]
We'll be able to write this bc a new version of the Application Insights library is released which includes `.CustomDimensions` where our custom (correlation) properties will be located.
