### ISSUE TITLE
Dependency docs should have less duplication

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#95]
Dependency docs should have less duplication as we are repeating how to:
- Measure with `DependencyMeasurement`
- Provide context

We should move those to a dedicated section to remove the duplication.

**Comment by stijnmoreels** [comment]
I'll leave the docs of upcoming dependency tracking then open, so we can then in the future just add the `.AddIoTHubDependency` method name to a list or some sort.
